const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const state={screen:'landing',roomCode:'',world:{occasion:'生日',honoree:'重要的人',date:'',invite:'今晚，我们偷偷在这里等你。',theme:'cream',music:'birthday',customMusicName:'',backdrop:''},player:{id:uid(),name:'朋友',hair:'1',outfit:'coral',item:'🎁',x:50,y:80,host:false,celebrated:false},players:new Map(),channel:null,keys:new Set(),near:null,mementos:[],notes:[],photos:[],activity:[],audio:{ctx:null,master:null,playing:false,timer:null,volume:.42,customUrl:null,element:null,fx:true}};
const colors={coral:'#e98f92',blue:'#8fb6c9',sage:'#9bb59c',butter:'#f3c969'};
const fixedObjects=[{id:'notes',x:14,y:23,r:12,label:'看看留言墙'},{id:'photos',x:82,y:24,r:13,label:'看看照片墙'},{id:'cake',x:50,y:48,r:12,label:'靠近蛋糕'},{id:'gifts',x:82,y:57,r:12,label:'看看礼物角'},{id:'music',x:32,y:24,r:10,label:'播放房间音乐'},{id:'sofa',x:18,y:57,r:13,label:'坐一会儿'}];
const roomKey=c=>`pixel-memory-v7-${c}`;const memoryKey=c=>`pixel-memory-v7-memory-${c}`;
function currentMemory(){return {mementos:state.mementos,notes:state.notes,photos:state.photos,activity:state.activity.slice(-40)}}
function saveRoom(){if(!state.roomCode)return;localStorage.setItem(roomKey(state.roomCode),JSON.stringify(state.world));saveMemory();PixelNet?.updateRoom(state.roomCode,{world:state.world,memory:currentMemory()}).catch(()=>{})}
function saveMemory(){if(!state.roomCode)return;localStorage.setItem(memoryKey(state.roomCode),JSON.stringify(currentMemory()));PixelNet?.updateRoom(state.roomCode,{memory:currentMemory()}).catch(()=>{})}
function loadRoom(code){try{const w=JSON.parse(localStorage.getItem(roomKey(code)));if(w)state.world={...state.world,...w};const m=JSON.parse(localStorage.getItem(memoryKey(code)));if(m){state.mementos=m.mementos||[];state.notes=m.notes||[];state.photos=m.photos||[];state.activity=m.activity||[]}}catch(e){}}
async function loadRoomRemote(code){loadRoom(code);if(!window.PixelNet?.enabled)return false;try{const r=await PixelNet.getRoom(code);if(r.world)state.world={...state.world,...r.world};if(r.memory){state.mementos=r.memory.mementos||[];state.notes=r.memory.notes||[];state.photos=r.memory.photos||[];state.activity=r.memory.activity||[]}localStorage.setItem(roomKey(code),JSON.stringify(state.world));localStorage.setItem(memoryKey(code),JSON.stringify(currentMemory()));return true}catch(e){return false}}
function randomCode(){const chars='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join('')}
function escapeHTML(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(t){const el=$('#toast');el.textContent=t;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),1800)}
function showScreen(id){$$('.screen').forEach(s=>s.classList.toggle('active',s.id===id));state.screen=id;window.scrollTo({top:0,behavior:'smooth'});if(id==='world')setTimeout(()=>$('#worldStage').focus(),50)}
function addActivity(text){state.activity.push({id:uid(),time:new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),text});state.activity=state.activity.slice(-40);saveMemory();broadcast('memory');}

// tactile buttons
let fxCtx=null;function clickSound(freq=240,dur=.035){if(!state.audio.fx)return;try{fxCtx=fxCtx||new (window.AudioContext||window.webkitAudioContext)();const o=fxCtx.createOscillator(),g=fxCtx.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.025,fxCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,fxCtx.currentTime+dur);o.connect(g).connect(fxCtx.destination);o.start();o.stop(fxCtx.currentTime+dur)}catch(e){}}
function sparkAt(x,y){const layer=$('#pressFx');for(let i=0;i<5;i++){const s=document.createElement('i');s.className='press-spark';s.style.left=`${x}px`;s.style.top=`${y}px`;s.style.setProperty('--dx',`${(Math.random()-.5)*38}px`);s.style.setProperty('--dy',`${(Math.random()-.5)*32}px`);layer.appendChild(s);setTimeout(()=>s.remove(),450)}}
document.addEventListener('pointerdown',e=>{const b=e.target.closest('.press');if(!b)return;b.classList.add('is-down');const r=b.getBoundingClientRect();sparkAt(Math.min(r.right-8,Math.max(r.left+8,e.clientX)),Math.min(r.bottom-8,Math.max(r.top+8,e.clientY)));clickSound()});document.addEventListener('pointerup',()=>$$('.is-down').forEach(b=>b.classList.remove('is-down')));document.addEventListener('pointercancel',()=>$$('.is-down').forEach(b=>b.classList.remove('is-down')));

// navigation
$$('[data-go]').forEach(b=>b.onclick=()=>showScreen(b.dataset.go));$('#createWorldBtn').onclick=()=>showScreen('creator');$('#joinWorldBtn').onclick=()=>showScreen('joiner');
$('#heroDoorbell').onclick=()=>{const a=$('#heroArrival');a.classList.remove('hidden');$('#heroDoorbell').innerHTML='<span>门开了</span><i></i>';toast('里面的人听见门铃了。');setTimeout(()=>a.classList.add('hidden'),2600)};
$$('[data-occasion]').forEach(b=>b.onclick=()=>{$$('[data-occasion]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.world.occasion=b.dataset.occasion});
$$('[data-theme]').forEach(b=>b.onclick=()=>{$$('[data-theme]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.world.theme=b.dataset.theme});
$$('[data-music]').forEach(b=>b.onclick=()=>{$$('[data-music]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.world.music=b.dataset.music});
$('#creatorUploadMusic').onclick=()=>$('#musicUploadInput').click();$('#musicUploadInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.world.music='custom';state.world.customMusicName=f.name;$('#creatorMusicName').textContent=f.name;state.audio.customUrl=URL.createObjectURL(f);toast('已经把这首歌带进房间了')};
$('#continueCreateBtn').onclick=async()=>{state.world.honoree=$('#honoreeInput').value.trim()||'重要的人';state.world.date=$('#dateInput').value;state.world.invite=$('#inviteInput').value.trim()||'今晚，我们偷偷在这里等你。';state.roomCode=randomCode();state.mementos=[];state.notes=[];state.photos=[];state.activity=[];localStorage.setItem(roomKey(state.roomCode),JSON.stringify(state.world));localStorage.setItem(memoryKey(state.roomCode),JSON.stringify(currentMemory()));if(window.PixelNet?.enabled){try{await PixelNet.createRoom(state.roomCode,state.world,currentMemory());toast(`联网房间 ${state.roomCode} 已创建`)}catch(e){toast(`门牌号 ${state.roomCode} 已生成 · 当前使用本地模式`)}}else toast(`门牌号 ${state.roomCode} 已生成`);showScreen('avatarBuilder')};
$('#joinCodeBtn').onclick=async()=>{const code=$('#joinCodeInput').value.trim().toUpperCase();if(code.length!==6)return toast('请输入 6 位门牌号');state.roomCode=code;const remote=await loadRoomRemote(code);if(window.PixelNet?.enabled&&!remote)return toast('没有找到这个联网房间，请检查邀请码或服务器地址');showScreen('avatarBuilder')};

// avatar
$$('[data-hair]').forEach(b=>b.onclick=()=>{$$('[data-hair]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.player.hair=b.dataset.hair;renderAvatar()});
$$('[data-outfit]').forEach(b=>b.onclick=()=>{$$('[data-outfit]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.player.outfit=b.dataset.outfit;renderAvatar()});
$$('[data-item]').forEach(b=>b.onclick=()=>{$$('[data-item]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.player.item=b.dataset.item;renderAvatar()});
function renderAvatar(){const p=$('#avatarPreview');p.className=`avatar-preview hair-${state.player.hair} outfit-${state.player.outfit}`;$('.held',p).textContent=state.player.item}renderAvatar();
$('#enterWorldBtn').onclick=()=>{state.player.name=$('#playerNameInput').value.trim()||'朋友';state.player.host=$('#hostToggle').checked;state.player.x=50+Math.random()*8-4;state.player.y=79+Math.random()*4-2;state.player.celebrated=false;enterWorld()};

// room network
function setupChannel(){if(state.channel)state.channel.close();state.channel=window.PixelNet?PixelNet.createChannel(`pixel-memory-v9-live-${state.roomCode}`,state.roomCode,state.player.id):(('BroadcastChannel'in window)?new BroadcastChannel(`pixel-memory-v9-live-${state.roomCode}`):null);if(!state.channel)return;state.channel.onmessage=e=>{const m=e.data;if(!m||m.sender===state.player.id)return;if(['hello','state','move','celebrate'].includes(m.type)&&m.player){state.players.set(m.player.id,{...m.player,lastSeen:Date.now()});if(m.type==='hello')broadcast('state');renderPlayers();renderCelebrateStatus()}if(m.type==='chat'&&m.player){state.players.set(m.player.id,{...m.player,lastSeen:Date.now()});renderPlayers();bubble(m.player.id,m.text)}if(m.type==='voice'&&m.player){state.players.set(m.player.id,{...m.player,lastSeen:Date.now()});renderPlayers();bubble(m.player.id,'🎙️ 留了一段声音');if(m.url)showVoiceToast(m.player.name,m.url)}if(m.type==='reaction'&&m.player){state.players.set(m.player.id,{...m.player,lastSeen:Date.now()});renderPlayers();reaction(m.player.id,m.emoji)}if(m.type==='bump'){bumpPlayer(m.target)}if(m.type==='memory'){if(m.world)state.world={...state.world,...m.world};if(m.memory){state.mementos=m.memory.mementos||[];state.notes=m.memory.notes||[];state.photos=m.memory.photos||[];state.activity=m.memory.activity||[];localStorage.setItem(memoryKey(state.roomCode),JSON.stringify(currentMemory()))}else loadMemoryOnly();renderMementos()}if(m.type==='leave'&&m.player){state.players.delete(m.player.id);renderPlayers();renderCelebrateStatus()}}}
function broadcast(type,extra={}){const payload={type,sender:state.player.id,player:{...state.player},...extra};if(type==='memory')payload.memory=currentMemory();state.channel?.postMessage(payload)}
function showVoiceToast(name,url){toast(`${name} 发来一段语音`);try{const a=new Audio(url);a.volume=.8;a.play().catch(()=>{})}catch(_){}}
function loadMemoryOnly(){try{const m=JSON.parse(localStorage.getItem(memoryKey(state.roomCode)));if(m){state.mementos=m.mementos||[];state.notes=m.notes||[];state.photos=m.photos||[];state.activity=m.activity||[]}}catch(e){}}
function enterWorld(){if(!state.roomCode)state.roomCode=randomCode();loadRoom(state.roomCode);state.players.clear();state.players.set(state.player.id,{...state.player,lastSeen:Date.now()});setupChannel();$('#roomCodeLabel').textContent=state.roomCode;$('#worldTitle').textContent=`${state.world.honoree}的${state.world.occasion}`;$('#worldSubtitle').textContent=state.world.invite;const stage=$('#worldStage');stage.className=`world-stage pixel-frame theme-${state.world.theme}`;applyBackdrop();renderPlayers();renderMementos();renderCelebrateStatus();showScreen('world');addActivity(`${state.player.name} 推开门进来了`);broadcast('hello');history.replaceState({},'',`${location.pathname}?room=${state.roomCode}`)}
function renderPlayers(){const now=Date.now();for(const [id,p] of state.players)if(id!==state.player.id&&now-(p.lastSeen||0)>16000)state.players.delete(id);const layer=$('#playersLayer');layer.innerHTML='';for(const [id,p] of state.players){const e=document.createElement('div');e.className=`player hair-${p.hair}${id===state.player.id?' me':''}`;e.dataset.id=id;e.style.left=`${p.x}%`;e.style.top=`${p.y}%`;e.style.setProperty('--shirt',colors[p.outfit]||colors.coral);e.innerHTML=`${p.host?'<span class="host-crown">✦</span>':''}<span class="player-name">${escapeHTML(p.name)}</span><span class="player-item">${p.item}</span>`;layer.appendChild(e)}$('#onlineCount').textContent=state.players.size;$('#globalStatus').textContent=state.screen==='world'?`${state.players.size} 个小人正在同一间房`:'今晚有人在等你'}
function bumpPlayer(id){const el=$(`.player[data-id="${id}"]`);if(!el)return;el.classList.remove('bump');void el.offsetWidth;el.classList.add('bump');setTimeout(()=>el.classList.remove('bump'),250)}
setInterval(()=>{if(state.screen==='world')broadcast('state')},5000);
window.addEventListener('beforeunload',()=>broadcast('leave'));

// movement + collision
const stage=$('#worldStage');stage.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(['arrowleft','arrowright','arrowup','arrowdown','w','a','s','d','e'].includes(k))e.preventDefault();if(k==='e'){interactNear();return}state.keys.add(k)});stage.addEventListener('keyup',e=>state.keys.delete(e.key.toLowerCase()));stage.addEventListener('blur',()=>state.keys.clear());
function gameLoop(){if(state.screen==='world'){let dx=0,dy=0;const sp=.42;if(state.keys.has('a')||state.keys.has('arrowleft'))dx-=sp;if(state.keys.has('d')||state.keys.has('arrowright'))dx+=sp;if(state.keys.has('w')||state.keys.has('arrowup'))dy-=sp;if(state.keys.has('s')||state.keys.has('arrowdown'))dy+=sp;if(dx||dy){let nx=Math.min(96,Math.max(3,state.player.x+dx)),ny=Math.min(92,Math.max(10,state.player.y+dy));let hit=null;for(const [id,p] of state.players){if(id===state.player.id)continue;if(Math.hypot(nx-p.x,ny-p.y)<4.3){hit={id,p};break}}if(hit){nx=state.player.x-dx*.65;ny=state.player.y-dy*.65;bumpPlayer(state.player.id);broadcast('bump',{target:hit.id});reaction(state.player.id,'✦');clickSound(145,.025)}state.player.x=nx;state.player.y=ny;state.players.set(state.player.id,{...state.player,lastSeen:Date.now()});renderPlayers();broadcast('move');updateNear()}}requestAnimationFrame(gameLoop)}requestAnimationFrame(gameLoop);
function updateNear(){let best=null,d=999;for(const o of fixedObjects){const nd=Math.hypot(state.player.x-o.x,state.player.y-o.y);if(nd<o.r&&nd<d){best={type:'fixed',...o};d=nd}}for(const m of state.mementos){const nd=Math.hypot(state.player.x-m.x,state.player.y-m.y);if(nd<7&&nd<d){best={type:'memento',...m,label:`拾起「${m.title}」`};d=nd}}state.near=best;$$('.memento').forEach(x=>x.classList.remove('near'));const prompt=$('#nearPrompt');if(best){prompt.classList.remove('hidden');$('span',prompt).textContent=best.label;if(best.type==='memento')$(`.memento[data-id="${best.id}"]`)?.classList.add('near')}else prompt.classList.add('hidden')}
function interactNear(){if(!state.near)return toast('再靠近一点点。');if(state.near.type==='memento')return openMementoDetail(state.near);const id=state.near.id;if(id==='notes')openNotesDrawer();if(id==='photos')openPhotosDrawer();if(id==='gifts')openMementosDrawer();if(id==='music')openMusicDrawer();if(id==='cake')openCelebrationPrep();if(id==='sofa'){reaction(state.player.id,'☕');bubble(state.player.id,'坐一会儿。')}}

// dock
$$('[data-dock]').forEach(b=>b.onclick=()=>{const a=b.dataset.dock;if(a==='talk')toggleTalk();if(a==='hug')doHug();if(a==='note')openNoteModal();if(a==='memento')openMementoModal();if(a==='photo')takePhoto();if(a==='celebrate')pressCelebrate();if(a==='music')openMusicDrawer()});
function toggleTalk(){$('#talkPopover').classList.toggle('hidden')}
$$('[data-say]').forEach(b=>b.onclick=()=>sendChat(b.dataset.say));$('#sendChatBtn').onclick=()=>{const t=$('#chatInput').value.trim();if(t){sendChat(t);$('#chatInput').value=''}};$('#chatInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('#sendChatBtn').click()});
function sendChat(t){bubble(state.player.id,t);broadcast('chat',{text:t})}function bubble(id,t){const p=state.players.get(id);if(!p)return;const e=document.createElement('div');e.className='chat-bubble';e.style.left=`${p.x}%`;e.style.top=`${p.y-4}%`;e.textContent=t;$('#bubbleLayer').appendChild(e);setTimeout(()=>e.remove(),3200)}
function reaction(id,emoji){const p=state.players.get(id);if(!p)return;const e=document.createElement('div');e.className='reaction-pop';e.style.left=`${p.x}%`;e.style.top=`${p.y-3}%`;e.textContent=emoji;$('#reactionLayer').appendChild(e);setTimeout(()=>e.remove(),1350)}
function nearestPlayer(max=11){let best=null,d=max;for(const [id,p] of state.players){if(id===state.player.id)continue;const nd=Math.hypot(state.player.x-p.x,state.player.y-p.y);if(nd<d){best={id,p};d=nd}}return best}
function doHug(){const n=nearestPlayer();if(!n)return toast('靠近一个朋友，再抱一下。');reaction(state.player.id,'♡');reaction(n.id,'♡');broadcast('reaction',{emoji:'♡'});bumpPlayer(state.player.id);bumpPlayer(n.id);addActivity(`${state.player.name} 抱了抱 ${n.p.name}`);toast(`抱到 ${n.p.name} 了`)}

// modal helpers
function openModal(ey,title,html){$('#modalEyebrow').textContent=ey;$('#modalTitle').textContent=title;$('#modalBody').innerHTML=html;$('#modal').classList.remove('hidden');$('#modal').setAttribute('aria-hidden','false')}function closeModal(){$('#modal').classList.add('hidden');$('#modal').setAttribute('aria-hidden','true')}$$('[data-close-modal]').forEach(x=>x.onclick=closeModal);
function openNoteModal(){openModal('LEAVE A LITTLE TRACE','在这里留下一句话',`<div class="modal-form"><label class="field"><span>别人以后走到这里，也能看到它</span><textarea id="noteText" rows="4" maxlength="120" placeholder="今年也要很开心。"></textarea></label><button id="saveNoteBtn" class="button primary full press">把这句话贴到墙上 <span>→</span></button></div>`);setTimeout(()=>$('#saveNoteBtn').onclick=()=>{const t=$('#noteText').value.trim();if(!t)return toast('先写一句话');state.notes.push({id:uid(),by:state.player.name,text:t,time:Date.now()});addActivity(`${state.player.name} 在留言墙贴了一张纸条`);saveMemory();broadcast('memory');reaction(state.player.id,'✎');closeModal();toast('它已经贴在墙上了')},0)}
function openMementoModal(){let type='🎁',photo='';openModal('DROP A MEMORY','在脚边放下一件纪念物',`<div class="modal-form"><div class="type-grid"><button class="type-choice selected press" data-mtype="🎁">🎁</button><button class="type-choice press" data-mtype="✉️">✉️</button><button class="type-choice press" data-mtype="🌷">🌷</button><button class="type-choice press" data-mtype="🎫">🎫</button><button class="type-choice press" data-mtype="📷">📷</button></div><label class="field"><span>给它一个名字</span><input id="mTitle" maxlength="28" placeholder="例如：2019 年的第一张合照"></label><label class="field"><span>它为什么重要？</span><textarea id="mMeaning" rows="4" maxlength="180" placeholder="那天我们第一次一起旅行，回程坐错了车。"></textarea></label><div class="photo-upload-box"><span id="mPhotoState">可以加一张照片，把它做成地上的小相框</span><button id="pickMPhoto" class="button secondary small press">选择照片</button></div><button id="dropMBtn" class="button primary full press">就放在我现在站的位置 <span>↓</span></button></div>`);setTimeout(()=>{$$('[data-mtype]').forEach(b=>b.onclick=()=>{$$('[data-mtype]').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');type=b.dataset.mtype});$('#pickMPhoto').onclick=()=>$('#mementoPhotoInput').click();$('#mementoPhotoInput').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{photo=rd.result;$('#mPhotoState').textContent=f.name};rd.readAsDataURL(f)};$('#dropMBtn').onclick=()=>{const title=$('#mTitle').value.trim()||'一件小东西',meaning=$('#mMeaning').value.trim()||'有人觉得它值得被留下。';state.mementos.push({id:uid(),type,photo,title,meaning,by:state.player.name,x:state.player.x+2,y:state.player.y+2,time:Date.now()});addActivity(`${state.player.name} 放下了「${title}」`);saveMemory();broadcast('memory');renderMementos();closeModal();reaction(state.player.id,'✦');toast('它留在这里了')}} ,0)}
function renderMementos(){const layer=$('#mementoLayer');layer.innerHTML='';state.mementos.forEach(m=>{const e=document.createElement('div');e.className=`memento${m.photo?' photo':''}`;e.dataset.id=m.id;e.style.left=`${m.x}%`;e.style.top=`${m.y}%`;const bg=m.photo?`style="background-image:url('${m.photo.replace(/'/g,"%27")}')"`:'';e.innerHTML=`<div class="object" ${bg}>${m.photo?'':m.type}</div>`;layer.appendChild(e)});updateNear();renderCelebrateStatus()}
function openMementoDetail(m){openModal('YOU FOUND SOMETHING',escapeHTML(m.title),`${m.photo?`<img class="memory-detail-photo" src="${m.photo}" alt="${escapeHTML(m.title)}">`:''}<p style="line-height:1.8;font-size:11px;color:#6f5f56">${escapeHTML(m.meaning)}</p><div class="memory-detail-meta">${escapeHTML(m.by)} 把它留在这里 · ${new Date(m.time).toLocaleDateString('zh-CN')}</div>`);reaction(state.player.id,'✦')}
function takePhoto(){const names=[...state.players.values()].map(p=>p.name);state.photos.push({id:uid(),by:state.player.name,names,time:Date.now()});addActivity(`${state.player.name} 按下快门，${names.length} 个人被拍进了合影`);saveMemory();broadcast('memory');reaction(state.player.id,'📷');toast(`咔嚓！${names.length} 个人被拍进去了`)}

// drawer
function showDrawer(title,html){$('#drawerTitle').textContent=title;$('#drawerBody').innerHTML=html;$('#roomDrawer').classList.remove('hidden');$('#roomDrawer').setAttribute('aria-hidden','false')}function closeDrawer(){$('#roomDrawer').classList.add('hidden');$('#roomDrawer').setAttribute('aria-hidden','true')}$('#closeRoomDrawer').onclick=closeDrawer;
$('#onlinePill').onclick=openPeopleDrawer;function openPeopleDrawer(){showDrawer('今晚在这里',`<div class="drawer-section"><h4>ONLINE NOW</h4><div class="people-list">${[...state.players.values()].map(p=>`<div class="person-row"><span>${p.host?'✦ ':''}${escapeHTML(p.name)}</span><span>${p.item}</span></div>`).join('')}</div></div><div class="drawer-section"><h4>刚刚发生</h4><div class="activity-list">${state.activity.slice().reverse().slice(0,12).map(a=>`<div class="activity-row"><span>${escapeHTML(a.text)}</span><small>${a.time}</small></div>`).join('')||'<div class="activity-row">还没有什么发生。</div>'}</div></div>`)}
function openNotesDrawer(){showDrawer('留言墙',`<div class="drawer-section"><h4>${state.notes.length} 张纸条</h4><div class="activity-list">${state.notes.slice().reverse().map(n=>`<div class="activity-row" style="display:block"><b>${escapeHTML(n.by)}</b><p style="margin:6px 0 0;line-height:1.55">${escapeHTML(n.text)}</p></div>`).join('')||'<div class="activity-row">墙还是空的。</div>'}</div></div><button class="button primary full press" id="drawerAddNote">再留一句</button>`);setTimeout(()=>$('#drawerAddNote').onclick=openNoteModal,0)}
function openPhotosDrawer(){showDrawer('今晚的合影',`<div class="drawer-section"><h4>${state.photos.length} 次快门</h4><div class="activity-list">${state.photos.slice().reverse().map(p=>`<div class="activity-row" style="display:block"><b>📷 ${p.names.map(escapeHTML).join('、')}</b><p style="margin:5px 0 0">${new Date(p.time).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}</p></div>`).join('')||'<div class="activity-row">还没人按下快门。</div>'}</div></div>`)}
function openMementosDrawer(){showDrawer('散落的纪念物',`<div class="drawer-section"><h4>${state.mementos.length} 件东西</h4><div class="activity-list">${state.mementos.slice().reverse().map(m=>`<div class="activity-row"><span>${m.type} ${escapeHTML(m.title)}</span><small>${escapeHTML(m.by)}</small></div>`).join('')||'<div class="activity-row">地上还空空的。</div>'}</div></div>`)}
$('#worldSettingsBtn').onclick=()=>showDrawer('房间设置',`<div class="drawer-section"><h4>ROOM LOOK</h4><div class="settings-grid"><button id="changeBackdrop">▣ 上传背景照片<br><small>把熟悉的地方放进大厅</small></button><button id="clearBackdrop">⌫ 恢复像素场景<br><small>回到默认布置</small></button></div></div><div class="drawer-section"><h4>SOUND</h4><button id="settingsMusic" class="button secondary full press">♫ 打开音乐控制</button></div><div class="drawer-section"><h4>THIS ROOM</h4><div class="person-row"><span>门牌号</span><b>${state.roomCode}</b></div><div class="person-row"><span>纪念物</span><b>${state.mementos.length}</b></div><div class="person-row"><span>留言</span><b>${state.notes.length}</b></div><div class="person-row"><span>合影</span><b>${state.photos.length}</b></div><button id="openKeepsakeSettings" class="button warm full press" style="margin-top:8px">✦ 打开纪念卡</button></div>`);setTimeout(()=>{$('#changeBackdrop').onclick=()=>$('#backdropUploadInput').click();$('#clearBackdrop').onclick=()=>{state.world.backdrop='';saveRoom();applyBackdrop();toast('已经恢复成像素场景')};$('#settingsMusic').onclick=openMusicDrawer;$('#openKeepsakeSettings').onclick=openKeepsake},0);
$('#backdropUploadInput').onchange=e=>{const f=e.target.files[0];if(!f)return;if(f.size>2.3*1024*1024)toast('演示版建议使用 2MB 以内的图片');const rd=new FileReader();rd.onload=()=>{state.world.backdrop=rd.result;saveRoom();applyBackdrop();toast('这张照片已经成为房间背景')};rd.readAsDataURL(f)};function applyBackdrop(){const b=$('#customBackdrop'),stage=$('#worldStage');if(state.world.backdrop){b.style.backgroundImage=`url('${state.world.backdrop}')`;b.classList.add('on');stage.classList.add('has-backdrop')}else{b.style.backgroundImage='';b.classList.remove('on');stage.classList.remove('has-backdrop')}}

// music: synth loops + custom audio
function ensureAudio(){if(state.audio.ctx)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;state.audio.ctx=new C();state.audio.master=state.audio.ctx.createGain();state.audio.master.gain.value=state.audio.volume;state.audio.master.connect(state.audio.ctx.destination)}
const seqs={birthday:[261.6,261.6,293.7,261.6,349.2,329.6,261.6,261.6,293.7,261.6,392,349.2],starlight:[220,277.2,329.6,277.2,246.9,329.6,370,329.6],cozy:[196,246.9,293.7,246.9,220,261.6,329.6,261.6]};
function stopMusic(){state.audio.playing=false;clearInterval(state.audio.timer);state.audio.timer=null;if(state.audio.element){state.audio.element.pause();state.audio.element=null}}
function startMusic(){stopMusic();state.audio.playing=true;if(state.world.music==='custom'&&state.audio.customUrl){const a=new Audio(state.audio.customUrl);a.loop=true;a.volume=state.audio.volume;a.play().catch(()=>{});state.audio.element=a;return}ensureAudio();if(!state.audio.ctx)return;let i=0;const seq=seqs[state.world.music]||seqs.birthday;const play=()=>{if(!state.audio.playing)return;const o=state.audio.ctx.createOscillator(),g=state.audio.ctx.createGain();o.type='square';o.frequency.value=seq[i++%seq.length];g.gain.setValueAtTime(.018,state.audio.ctx.currentTime);g.gain.exponentialRampToValueAtTime(.001,state.audio.ctx.currentTime+.24);o.connect(g).connect(state.audio.master);o.start();o.stop(state.audio.ctx.currentTime+.25)};play();state.audio.timer=setInterval(play,420)}
$('#globalSoundBtn').onclick=()=>{if(state.screen==='world')openMusicDrawer();else{state.audio.fx=!state.audio.fx;toast(`按钮触感音已${state.audio.fx?'开启':'关闭'}`)}};
function openMusicDrawer(){showDrawer('房间音乐',`<div class="drawer-section music-panel"><h4>ROOM SOUNDTRACK</h4>${[['birthday','生日快乐 · 8-bit'],['starlight','夜晚微光'],['cozy','暖灯客厅']].map(([k,n])=>`<button class="track-button press ${state.world.music===k?'selected':''}" data-track="${k}"><span>${n}</span><b>${state.world.music===k&&state.audio.playing?'PLAYING':'▶'}</b></button>`).join('')}<button id="drawerUploadTrack" class="track-button press"><span>＋ 上传自己的音乐</span><b>${escapeHTML(state.world.customMusicName||'FILE')}</b></button><button id="musicPlayBtn" class="button primary full press">${state.audio.playing?'暂停音乐':'播放音乐'}</button><div class="volume-row"><span>房间音量</span><input id="volumeRange" type="range" min="0" max="100" value="${Math.round(state.audio.volume*100)}"><b>${Math.round(state.audio.volume*100)}%</b></div></div><div class="drawer-section"><button id="fxBtn" class="button secondary full press">按钮触感音：${state.audio.fx?'开':'关'}</button></div>`);setTimeout(()=>{$$('[data-track]').forEach(b=>b.onclick=()=>{state.world.music=b.dataset.track;saveRoom();startMusic();openMusicDrawer()});$('#drawerUploadTrack').onclick=()=>$('#musicUploadInput').click();$('#musicPlayBtn').onclick=()=>{state.audio.playing?stopMusic():startMusic();openMusicDrawer()};$('#volumeRange').oninput=e=>{state.audio.volume=+e.target.value/100;if(state.audio.master)state.audio.master.gain.value=state.audio.volume;if(state.audio.element)state.audio.element.volume=state.audio.volume;e.target.nextElementSibling.textContent=`${e.target.value}%`};$('#fxBtn').onclick=()=>{state.audio.fx=!state.audio.fx;openMusicDrawer()}},0)}

// collective celebration
function openCelebrationPrep(){toast('大家都准备好时，从底部按下「庆祝」')}let celebrationCompleted=false;function renderCelebrateStatus(){const ps=[...state.players.values()],n=ps.filter(p=>p.celebrated).length;$('#celebrateDockStatus').textContent=`${n}/${Math.max(ps.length,1)}`;if(n<ps.length)celebrationCompleted=false;if(ps.length>0&&n===ps.length&&!celebrationCompleted){celebrationCompleted=true;triggerCelebration(false)}}
let celebrationShown=false;function pressCelebrate(){state.player.celebrated=!state.player.celebrated;state.players.set(state.player.id,{...state.player,lastSeen:Date.now()});broadcast('celebrate');renderPlayers();renderCelebrateStatus();reaction(state.player.id,state.player.celebrated?'✦':'·');toast(state.player.celebrated?'你按下了庆祝，等其他人一起。':'你取消了准备')}
function triggerCelebration(force){if(celebrationShown&&!force)return;celebrationShown=true;$('#celebrationPeople').innerHTML=[...state.players.values()].map(p=>`<span>${escapeHTML(p.name.slice(0,2))}</span>`).join('');$('#celebrationOverlay').classList.remove('hidden');$('#celebrationOverlay').setAttribute('aria-hidden','false');confetti();addActivity('所有人一起按下了「庆祝」');setTimeout(()=>{celebrationShown=false},4000)}
function confetti(){const layer=$('#confettiLayer');layer.innerHTML='';const cs=['#e98f92','#f3c969','#8fb6c9','#9bb59c','#fffaf2'];for(let i=0;i<75;i++){const x=document.createElement('i');x.className='confetti';x.style.left=`${Math.random()*100}%`;x.style.background=cs[i%cs.length];x.style.animationDelay=`${Math.random()*.8}s`;x.style.animationDuration=`${2+Math.random()*1.5}s`;layer.appendChild(x)}}
$('#closeCelebration').onclick=()=>{$('#celebrationOverlay').classList.add('hidden');$('#celebrationOverlay').setAttribute('aria-hidden','true')};$('#openKeepsakeFromCelebration').onclick=()=>{$('#celebrationOverlay').classList.add('hidden');openKeepsake()};

// keepsake
function openKeepsake(){const ps=[...state.players.values()];$('#keepsakeDate').textContent=state.world.date?new Date(`${state.world.date}T00:00`).toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'}):new Date().toLocaleDateString('zh-CN',{year:'numeric',month:'long',day:'numeric'});$('#keepsakeTitle').textContent=`${state.world.honoree}的${state.world.occasion}`;$('#keepsakeQuote').textContent=`“${state.world.invite}”`;$('#keepsakePeople').innerHTML=ps.map(p=>`<span>${escapeHTML(p.name.slice(0,2))}</span>`).join('');$('#keepVisitors').textContent=ps.length;$('#keepNotes').textContent=state.notes.length;$('#keepMementos').textContent=state.mementos.length;$('#keepPhotos').textContent=state.photos.length;$('#keepLastLine').textContent=state.notes.length?`“${state.notes[state.notes.length-1].text}” — ${state.notes[state.notes.length-1].by}`:'这里还在等第一句话。';$('#keepCode').textContent=`ROOM · ${state.roomCode}`;$('#keepsakeOverlay').classList.remove('hidden');$('#keepsakeOverlay').setAttribute('aria-hidden','false')}$$('[data-close-keepsake]').forEach(x=>x.onclick=()=>$('#keepsakeOverlay').classList.add('hidden'));
$('#copyKeepsakeInvite').onclick=$('#copyInviteBtn').onclick=async()=>{const u=`${location.origin}${location.pathname}?room=${state.roomCode}`,t=`来我的小小世界吧｜门牌号 ${state.roomCode}\n${u}`;try{await navigator.clipboard.writeText(t);toast('邀请链接和门牌号已复制')}catch(e){toast(`门牌号：${state.roomCode}`)}};
$('#saveKeepsakeBtn').onclick=()=>{const c=document.createElement('canvas');c.width=1080;c.height=1350;const g=c.getContext('2d');g.fillStyle='#fff3e5';g.fillRect(0,0,c.width,c.height);g.fillStyle='#f3c969';g.fillRect(760,0,320,260);g.fillStyle='#9a705d';g.font='bold 28px monospace';g.fillText('PIXEL MEMORY',70,90);g.font='bold 62px sans-serif';g.fillStyle='#554841';g.fillText(`${state.world.honoree}的${state.world.occasion}`,70,240);g.font='28px sans-serif';g.fillStyle='#8c7d73';wrapText(g,`“${state.world.invite}”`,70,315,900,45);g.fillStyle='#e98f92';g.fillRect(70,470,940,4);const stats=[['来过',state.players.size],['留言',state.notes.length],['纪念物',state.mementos.length],['合影',state.photos.length]];stats.forEach((s,i)=>{const x=90+i*235;g.fillStyle='#554841';g.font='bold 58px monospace';g.fillText(String(s[1]),x,620);g.fillStyle='#8c7d73';g.font='24px sans-serif';g.fillText(s[0],x,660)});g.fillStyle='#f0dfcf';g.fillRect(70,760,940,250);g.fillStyle='#554841';g.font='28px sans-serif';wrapText(g,state.notes.length?`“${state.notes[state.notes.length-1].text}” — ${state.notes[state.notes.length-1].by}`:'这里还在等第一句话。',105,830,860,46);g.fillStyle='#8c7d73';g.font='22px monospace';g.fillText(`ROOM · ${state.roomCode}`,70,1260);const a=document.createElement('a');a.download=`pixel-memory-${state.roomCode}.png`;a.href=c.toDataURL('image/png');a.click();toast('纪念卡已经生成')};
function wrapText(g,t,x,y,w,h){let line='';for(const ch of t){const test=line+ch;if(g.measureText(test).width>w){g.fillText(line,x,y);line=ch;y+=h}else line=test}g.fillText(line,x,y)}

$('#leaveWorldBtn').onclick=()=>{broadcast('leave');stopMusic();state.channel?.close();state.channel=null;showScreen('landing')};

// network status
if(window.PixelNet){PixelNet.onStatus(({status})=>{const el=$('#globalStatus');if(!el)return;if(status==='online')el.textContent='已连接 · 跨设备联机中';else if(status==='local')el.textContent='本地联机模式 · 配置服务器可跨设备';else if(status==='disconnected')el.textContent='网络断开，正在回到本地模式';});}

// auto join via URL
const q=new URLSearchParams(location.search),r=q.get('room');if(r&&r.length===6){$('#joinCodeInput').value=r.toUpperCase();showScreen('joiner')}
