# Generated by Django 5.2.17 on 2026-09-29 12:06

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=80, verbose_name='操作')),
                ('target', models.CharField(max_length=200, verbose_name='对象')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='详情')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('income', '收入'), ('expense', '支出'), ('bonus', '奖金'), ('api', 'API 成本')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额（元）')),
                ('occurred_on', models.DateField(verbose_name='发生日期')),
                ('memo', models.TextField(max_length=3000, verbose_name='说明')),
                ('receipt', models.FileField(blank=True, upload_to=core.models.private_path, validators=[core.models.validate_private_file], verbose_name='凭证')),
                ('receipt_name', models.CharField(blank=True, max_length=255, verbose_name='凭证原文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='作废时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='记账人')),
            ],
            options={
                'verbose_name': '财务记录',
                'verbose_name_plural': '财务记录',
                'ordering': ['-occurred_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True, verbose_name='邀请码摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='撤销时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_invites', to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
                ('used_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_invite', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '邀请码',
                'verbose_name_plural': '邀请码',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='任务名称')),
                ('description', models.TextField(verbose_name='任务说明')),
                ('due_date', models.DateField(verbose_name='截止日期')),
                ('progress', models.PositiveSmallIntegerField(default=0, verbose_name='进度（0-100）')),
                ('status', models.CharField(choices=[('open', '进行中'), ('submitted', '待审核'), ('completed', '已结项')], default='open', max_length=12, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='归档时间')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='负责人')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=3000, verbose_name='成果说明')),
                ('attachment', models.FileField(upload_to=core.models.private_path, validators=[core.models.validate_private_file], verbose_name='成果文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原文件名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('accepted', '已通过'), ('rejected', '已退回')], default='pending', max_length=12, verbose_name='审核状态')),
                ('review_note', models.TextField(blank=True, max_length=3000, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='提交者')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='core.task', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务成果',
                'verbose_name_plural': '任务成果',
                'ordering': ['-created_at'],
            },
        ),
    ]
