# Generated by Django 5.2.17 on 2026-10-01 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrated_public_experiments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=40)),
                ('last_message_id', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='比赛名称')),
                ('website', models.URLField(blank=True, verbose_name='官网链接')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='交付截止日期')),
                ('description', models.TextField(blank=True, max_length=5000, verbose_name='参赛目标与要求')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['deadline', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExperimentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('parameters', models.JSONField(default=list, verbose_name='参数模板')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='chat_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.chatmessage', verbose_name='聊天消息'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.experiment', verbose_name='实验记录'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='conclusion',
            field=models.TextField(blank=True, max_length=10000, verbose_name='结论与下一步'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='origin_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_records', to='core.task', verbose_name='来源任务'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='parameters',
            field=models.JSONField(blank=True, default=list, verbose_name='实验参数'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='purpose',
            field=models.TextField(blank=True, max_length=5000, verbose_name='实验目的'),
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('design', '实验设计'), ('execution', '实验过程'), ('analysis', '结果分析'), ('other', '其他事务')], default='other', max_length=12, verbose_name='任务类型'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='body',
            field=models.TextField(blank=True, max_length=2000, verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='room',
            field=models.CharField(choices=[('public', '公共聊天室'), ('developers', '公共讨论'), ('private', '私聊')], default='public', max_length=12, verbose_name='聊天室'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='procedure',
            field=models.TextField(blank=True, max_length=10000, verbose_name='方法与条件'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='result',
            field=models.TextField(blank=True, max_length=15000, verbose_name='实验结果'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recipient__isnull', False), ('room', 'private'), models.Q(('author', models.F('recipient')), _negated=True)), models.Q(('recipient__isnull', True), ('room__in', ['public', 'developers'])), _connector='OR'), name='chat_recipient_matches_room'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_competitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='competition',
            name='final_results',
            field=models.ManyToManyField(blank=True, related_name='competitions', to='core.submission', verbose_name='选用成果'),
        ),
        migrations.AddField(
            model_name='competition',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_competitions', to=settings.AUTH_USER_MODEL, verbose_name='比赛负责人'),
        ),
        migrations.AddField(
            model_name='task',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='core.competition', verbose_name='关联比赛'),
        ),
        migrations.AddField(
            model_name='experimenttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experiment_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(fields=('user', 'channel'), name='one_chat_read_state'),
        ),
        migrations.AddConstraint(
            model_name='experimenttemplate',
            constraint=models.UniqueConstraint(fields=('created_by', 'name'), name='unique_personal_experiment_template'),
        ),
    ]
