# Generated by Django 5.2.17 on 2026-10-01 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_research_competitions_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('task', '任务'), ('experiment', '实验'), ('entry', '财务记录'), ('claim', '报销申请'), ('announcement', '公告')], max_length=16)),
                ('announcement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.announcement')),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.expenseclaim')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.financeentry')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.experiment')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='core.chatmessage')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.task')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
