# Generated by Django 5.2.17 on 2026-10-02 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_chat_content_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='core.project', verbose_name='关联项目'),
        ),
    ]
