# Generated by Django 5.2.17 on 2026-10-02 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expenseclaim_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeentry',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finance_entries', to='core.project', verbose_name='关联项目'),
        ),
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='留空表示暂不设预算；成本汇总据此计算剩余与使用比例。', max_digits=12, null=True, verbose_name='项目预算（元）'),
        ),
    ]
