# Generated by Django 5.2.17 on 2026-10-02 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_normalise_user_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('reset', '重置密码')], default='reset', max_length=20, verbose_name='用途')),
                ('email', models.EmailField(max_length=254, verbose_name='发送到的邮箱')),
                ('code_hash', models.CharField(max_length=128, verbose_name='验证码摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='已尝试次数')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='使用时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL, verbose_name='账号')),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'used_at'], name='verify_code_lookup')],
            },
        ),
    ]
