# Generated by Django 5.2.17 on 2026-10-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_finance_recycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('reset', '重置密码'), ('bind', '绑定邮箱')], default='reset', max_length=20, verbose_name='用途'),
        ),
    ]
