# Generated by Django 5.2.17 on 2026-10-04 12:44

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_email_binding_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreadstate',
            name='cleared_through',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='removed_through',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='avatar',
            field=models.FileField(blank=True, upload_to=core.models.private_path, verbose_name='头像'),
        ),
    ]
