# Generated by Django 5.2.17 on 2026-10-05 01:10

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0011_alter_call_options'),
        ('core', '0019_avatars_conversation_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='运行名称')),
                ('status', models.CharField(choices=[('running', '运行中'), ('completed', '已完成'), ('failed', '失败')], default='running', max_length=16, verbose_name='状态')),
                ('parameters', models.TextField(blank=True, max_length=10000, verbose_name='参数与方法版本')),
                ('result', models.TextField(blank=True, max_length=30000, verbose_name='结果与数据说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('file', models.FileField(upload_to=core.models.private_path)),
                ('mime', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['created_at', 'pk'], 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'pk'], 'verbose_name': '聊天室消息', 'verbose_name_plural': '聊天室消息'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'pk'], 'verbose_name': '留言', 'verbose_name_plural': '留言'},
        ),
        migrations.AlterModelOptions(
            name='emailverificationcode',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': '邮箱验证码', 'verbose_name_plural': '邮箱验证码'},
        ),
        migrations.AlterModelOptions(
            name='expenseclaim',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': '报销申请', 'verbose_name_plural': '报销申请'},
        ),
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['-created_at', '-pk']},
        ),
        migrations.AlterModelOptions(
            name='invite',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': '邀请码', 'verbose_name_plural': '邀请码'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': '项目', 'verbose_name_plural': '项目'},
        ),
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ['-created_at', '-pk'], 'verbose_name': '成果', 'verbose_name_plural': '成果'},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='kind',
            field=models.CharField(choices=[('text', '消息'), ('notice', '系统提示'), ('sticker', '表情包')], default='text', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='quoted_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.chatmessage'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='system_gift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='aihub.pointgift'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='status',
            field=models.CharField(choices=[('design', '准备中'), ('running', '进行中'), ('completed', '已完成'), ('archived', '已归档')], default='design', max_length=16, verbose_name='进度'),
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['project', '-created_at', '-id'], name='experiment_project_recent'),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='experiment_runs', to='core.attachment'),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.experiment'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sticker',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_stickers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='core.sticker'),
        ),
        migrations.AddIndex(
            model_name='experimentrun',
            index=models.Index(fields=['experiment', '-created_at', '-id'], name='experiment_run_recent'),
        ),
    ]
