# Generated by Django 5.2.17 on 2026-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_existing_experiment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='release_data',
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='release_version',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True),
        ),
    ]
