# Generated by Django 5.2.17 on 2026-10-05 18:06

import core.tenancy
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_team(apps, schema_editor):
    Team = apps.get_model('core', 'Team')
    Team.objects.using(schema_editor.connection.alias).get_or_create(pk=1, defaults={'name': '原科研团队', 'slug': 'original-team'})


def migrate_memberships(apps, schema_editor):
    db = schema_editor.connection.alias
    User = apps.get_model(*settings.AUTH_USER_MODEL.split('.'))
    Profile = apps.get_model('core', 'MemberProfile')
    Membership = apps.get_model('core', 'TeamMembership')
    Team = apps.get_model('core', 'Team')
    profiles = {p.user_id:p for p in Profile.objects.using(db).all()}
    users = list(User.objects.using(db).order_by('pk'))
    owner = next((u for u in users if u.is_active and u.is_superuser), None) or next((u for u in users if u.is_active and u.is_staff), None)
    for user in users:
        profile = profiles.get(user.pk)
        role = 'owner' if owner and owner.pk == user.pk else 'admin' if user.is_staff else 'guest' if profile and profile.tier == 'normal' else 'member'
        Membership.objects.using(db).get_or_create(team_id=1, user=user, defaults={'role':role, 'active':user.is_active, 'deleted_at':profile.deleted_at if profile else None})
    if owner:
        Team.objects.using(db).filter(pk=1).update(owner=owner)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_member_account_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='团队名称')),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=40, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '团队所有者'), ('admin', '团队管理员'), ('member', '成员'), ('guest', '访客成员')], default='member', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='chatreadstate',
            name='one_chat_read_state',
        ),
        migrations.RemoveConstraint(
            model_name='experimenttemplate',
            name='unique_personal_experiment_template',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='release_version',
            field=models.CharField(blank=True, editable=False, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='number',
            field=models.CharField(max_length=80, verbose_name='实验编号'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='used_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='used_invites', to=settings.AUTH_USER_MODEL, verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(seed_team, migrations.RunPython.noop),
        migrations.AddField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='chatreference',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='experimenttemplate',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(fields=('team', 'release_version'), name='team_release_version'),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(fields=('team', 'user', 'channel'), name='one_chat_read_state'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('team', 'number'), name='team_experiment_number'),
        ),
        migrations.AddConstraint(
            model_name='experimenttemplate',
            constraint=models.UniqueConstraint(fields=('team', 'created_by', 'name'), name='unique_personal_experiment_template'),
        ),
        migrations.AddConstraint(
            model_name='teamcontact',
            constraint=models.UniqueConstraint(fields=('team',), name='contact_per_team'),
        ),
        migrations.AddConstraint(
            model_name='userpresence',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='presence_per_team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='core.team'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teammembership',
            index=models.Index(fields=['user', 'active'], name='membership_user_active'),
        ),
        migrations.AddConstraint(
            model_name='teammembership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='one_membership_per_team'),
        ),
        migrations.RunPython(migrate_memberships, migrations.RunPython.noop),
    ]
