# Generated by Django 5.2.17 on 2026-10-06 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_capacity(apps, schema_editor):
    Team=apps.get_model('core','Team');Membership=apps.get_model('core','TeamMembership')
    for team in Team.objects.all():
        count=Membership.objects.filter(team_id=team.pk,active=True,deleted_at__isnull=True).count()
        if count>team.member_limit:Team.objects.filter(pk=team.pk).update(member_limit=count)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_team_teammembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='restricted_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_team_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='introduction',
            field=models.TextField(blank=True, max_length=3000, verbose_name='团队介绍'),
        ),
        migrations.AddField(
            model_name='team',
            name='listed',
            field=models.BooleanField(default=False, verbose_name='展示在团队广场'),
        ),
        migrations.AddField(
            model_name='team',
            name='member_limit',
            field=models.PositiveIntegerField(default=10, verbose_name='成员上限'),
        ),
        migrations.AddField(
            model_name='team',
            name='research_area',
            field=models.CharField(blank=True, max_length=200, verbose_name='研究与业务方向'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='permissions',
            field=models.JSONField(blank=True, default=list, verbose_name='团队授权'),
        ),
        migrations.AddField(
            model_name='teammembership',
            name='position',
            field=models.CharField(blank=True, max_length=60, verbose_name='职务'),
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction', models.TextField(blank=True, max_length=4000)),
                ('skills', models.CharField(blank=True, max_length=500)),
                ('portfolio', models.URLField(blank=True, max_length=1000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeamCreationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64, unique=True)),
                ('member_limit', models.PositiveIntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_team_creation_invites', to=settings.AUTH_USER_MODEL)),
                ('created_team', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='redeemed_team_creation_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('manage_team_admission', '管理团队准入及规模')],
            },
        ),
        migrations.CreateModel(
            name='TeamOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=4000)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='openings', to='core.team')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TeamApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.TextField(max_length=5000)),
                ('portfolio', models.URLField(blank=True, max_length=1000)),
                ('note', models.TextField(blank=True, max_length=1000)),
                ('state', models.CharField(choices=[('pending', '待审核'), ('accepted', '已接受'), ('rejected', '未通过'), ('withdrawn', '已撤回'), ('joined', '已加入')], default='pending', max_length=12)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_applications', to=settings.AUTH_USER_MODEL)),
                ('invite', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.invite')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_team_applications', to=settings.AUTH_USER_MODEL)),
                ('opening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='core.teamopening')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('opening', 'applicant'), name='one_application_per_opening')],
            },
        ),
        migrations.RunPython(preserve_existing_capacity,migrations.RunPython.noop),
    ]
