# Generated by Django 5.2.17 on 2026-10-06 09:10

import core.tenancy
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_account_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'permissions': [('manage_platform_accounts', '封禁和注销平台账号')],
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('personal', '个人空间'), ('team', '团队公账户')], max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='announcement',
            name='team_release_version',
        ),
        migrations.RemoveConstraint(
            model_name='chatreadstate',
            name='one_chat_read_state',
        ),
        migrations.RemoveConstraint(
            model_name='experiment',
            name='team_experiment_number',
        ),
        migrations.RemoveConstraint(
            model_name='experimenttemplate',
            name='unique_personal_experiment_template',
        ),
        migrations.RemoveConstraint(
            model_name='teamcontact',
            name='contact_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='userpresence',
            name='presence_per_team',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='chatreadstate',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='chatreference',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='emailverificationcode',
            name='purpose',
            field=models.CharField(choices=[('reset', '重置密码'), ('bind', '绑定邮箱'), ('register', '注册邮箱验证')], default='reset', max_length=20, verbose_name='用途'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='experimenttemplate',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='platformaudit',
            name='actor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='platform_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platformaudit',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_workspace', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workspace',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workspace', to='core.team'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='chatreadstate',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='chatreference',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='comment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='competition',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='expenseclaim',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='experimentrun',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='experimenttemplate',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='financeentry',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='invite',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='submission',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='teamcontact',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='userpresence',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddConstraint(
            model_name='announcement',
            constraint=models.UniqueConstraint(fields=('workspace', 'release_version'), name='team_release_version'),
        ),
        migrations.AddConstraint(
            model_name='chatreadstate',
            constraint=models.UniqueConstraint(fields=('workspace', 'user', 'channel'), name='one_chat_read_state'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(fields=('workspace', 'number'), name='team_experiment_number'),
        ),
        migrations.AddConstraint(
            model_name='experimenttemplate',
            constraint=models.UniqueConstraint(fields=('workspace', 'created_by', 'name'), name='unique_personal_experiment_template'),
        ),
        migrations.AddConstraint(
            model_name='teamcontact',
            constraint=models.UniqueConstraint(fields=('workspace',), name='contact_per_team'),
        ),
        migrations.AddConstraint(
            model_name='userpresence',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='presence_per_team'),
        ),
        migrations.AddConstraint(
            model_name='workspace',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'personal'), ('owner__isnull', False), ('team__isnull', True)), models.Q(('kind', 'team'), ('owner__isnull', True), ('team__isnull', False)), _connector='OR'), name='workspace_exact_owner'),
        ),
    ]
