# Generated by Django 5.2.17 on 2026-10-06 09:21

import django.db.models.deletion
from django.db import migrations, models


def populate_spaces(apps,schema_editor):
    alias=schema_editor.connection.alias
    Space=apps.get_model('core','Workspace')
    Team=apps.get_model('core','Team')
    for team in Team.objects.using(alias).all():Space.objects.using(alias).get_or_create(team_id=team.pk,defaults={'kind':'team'})
    for user in apps.get_model('auth','User').objects.using(alias).all():Space.objects.using(alias).get_or_create(owner_id=user.pk,defaults={'kind':'personal'})
    mapping=dict(Space.objects.using(alias).filter(kind='team').values_list('team_id','pk'))
    for model in apps.get_models():
        if model._meta.app_label not in ('core','aihub'):continue
        fields={field.name for field in model._meta.fields}
        if 'workspace' not in fields or 'team' not in fields:continue
        for team_id,space_id in mapping.items():
            model._base_manager.using(alias).filter(team_id=team_id,workspace__isnull=True).update(workspace_id=space_id)


class Migration(migrations.Migration):

    dependencies = [
        ('aihub','0017_remove_allowance_allowance_per_team_and_more'),
        ('core', '0030_platformaudit_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatgroup',
            name='announcement',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='nickname',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='remark',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='quote',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='security_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='quote',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='chat_groups', to='core.team'),
        ),
        migrations.CreateModel(
            name='MessageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='message-uploads/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='core.groupmessage')),
                ('personal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uploads', to='core.personalmessage')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('message__isnull', True), ('personal__isnull', False)), models.Q(('message__isnull', False), ('personal__isnull', True)), _connector='OR'), name='upload_one_message')],
            },
        ),
        migrations.RunPython(populate_spaces,migrations.RunPython.noop),
    ]
