# Generated by Django 5.2.17 on 2026-10-06 09:21

import core.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_chatgroup_announcement_groupmember_muted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='chatreadstate',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='chatreference',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='experimentrun',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='experimenttemplate',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='financeentry',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='project',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='task',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='teamcontact',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='userpresence',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
    ]
