# Generated by Django 5.2.17 on 2026-10-06 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def retain_private_history(apps, schema_editor):
    Chat=apps.get_model('core','ChatMessage')
    Personal=apps.get_model('core','PersonalMessage')
    database=schema_editor.connection.alias
    for row in Chat._base_manager.using(database).filter(room='private').order_by('created_at','pk').iterator(chunk_size=500):
        quote={}
        if row.quoted_message_id:
            original=row.quoted_message
            profile=apps.get_model('core','MemberProfile').objects.using(database).filter(user_id=original.author_id).first()
            name=profile.nickname if profile and profile.nickname else original.author.username
            quote={'author':name,'body':'消息已撤回' if original.withdrawn_at else original.body[:500]}
        item=Personal.objects.using(database).create(legacy_message_id=row.pk,sender_id=row.author_id,
            recipient_id=row.recipient_id,body=row.body,quote=quote,withdrawn_at=row.withdrawn_at,sticker_id=row.sticker_id)
        Personal.objects.using(database).filter(pk=item.pk).update(created_at=row.created_at)
        item.hidden_by.add(*row.hidden_by.values_list('pk',flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_workspaceevent_chatgroup_active_chatgroup_is_default_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_messages', to='core.sticker'),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='hidden_by',
            field=models.ManyToManyField(blank=True, related_name='hidden_personal_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='legacy_message',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_record', to='core.chatmessage'),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='personalmessage',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_messages', to='core.sticker'),
        ),
        migrations.RunPython(retain_private_history,migrations.RunPython.noop),
    ]
