# Generated by Django 5.2.17 on 2026-10-06 11:35

from django.db import migrations, models


def verify_existing(apps,schema_editor):
    apps.get_model('core','PersonalMessage').objects.using(schema_editor.connection.alias).update(relation_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_groupmessage_hidden_by_groupmessage_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalmessage',
            name='relation_verified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(verify_existing,migrations.RunPython.noop),
    ]
