# Generated by Django 5.2.17 on 2026-10-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_personalmessage_relation_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalthreadread',
            name='cleared_through',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalthreadread',
            name='muted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalthreadread',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalthreadread',
            name='removed_through',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
