# Generated by Django 5.2.17 on 2026-10-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_registrationchallenge_registrationthrottle'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='disbanded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
