# Generated by Django 5.2.17 on 2026-10-06 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def pending_confirmation_notices(apps,schema_editor):
    Application=apps.get_model('core','TeamApplication')
    Notice=apps.get_model('core','AccountNotice')
    for item in Application.objects.using(schema_editor.connection.alias).filter(state='accepted').select_related('opening__team').iterator():
        Notice.objects.using(schema_editor.connection.alias).create(user_id=item.applicant_id,application_id=item.pk,
            title=item.opening.team.name+' 通过了你的申请',body='请确认是否加入该团队。确认后才成为团队成员。')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_team_disbanded_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='show_nicknames',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='AccountNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=1000)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teamapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='account_notice_unread')],
            },
        ),
        migrations.RunPython(pending_confirmation_notices,migrations.RunPython.noop),
    ]
