# Generated by Django 5.2.17 on 2026-10-07 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0020_personal_assistant_history'),
        ('core', '0040_collaboration_and_private_funding'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaim',
            name='settlement_kind',
            field=models.CharField(choices=[('cash', '现金报销'), ('api_quota', '团队 AI 额度')], default='cash', max_length=12, verbose_name='补助方式'),
        ),
        migrations.AlterField(
            model_name='expenseclaim',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=12, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='UsageReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18)),
                ('model_label', models.CharField(max_length=200)),
                ('occurred_at', models.DateTimeField()),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reimbursement_receipts', to='aihub.call')),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_receipts', to='core.expenseclaim')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('call',), name='one_active_usage_receipt')],
            },
        ),
    ]
