# Generated by Django 5.2.17 on 2026-10-07 05:28

import core.document_models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_complete_legacy_applications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='任务负责人'),
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('content', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, upload_to=core.document_models.document_file)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(default=dict)),
                ('file', models.FileField(blank=True, upload_to=core.document_models.document_file)),
                ('generation', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('draft', '修改中'), ('submitted', '待审核'), ('changes_requested', '需要调整'), ('merged', '已采纳'), ('rejected', '未采纳')], default='draft', max_length=20)),
                ('summary', models.CharField(blank=True, max_length=500)),
                ('review_note', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_drafts', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentversion')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='OfficeEditingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('generation', models.PositiveIntegerField()),
                ('closed', models.BooleanField(default=False)),
                ('save_requested', models.UUIDField(null=True)),
                ('save_completed', models.UUIDField(null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_sessions', to='core.documentdraft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('online', '在线文档'), ('docx', 'Word'), ('xlsx', 'Excel'), ('pdf', 'PDF')], default='online', max_length=12)),
                ('purpose', models.CharField(choices=[('notes', '资料'), ('plan', '规划'), ('result', '成果')], default='notes', max_length=12)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.competition')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_documents', to=settings.AUTH_USER_MODEL)),
                ('current', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.documentversion')),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.experiment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.task')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.shareddocument'),
        ),
        migrations.CreateModel(
            name='DocumentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.document_models.document_file)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.shareddocument')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentEditRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
                ('state', models.CharField(choices=[('pending', '待批准'), ('approved', '已批准'), ('rejected', '未批准')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='edit_requests', to='core.shareddocument')),
            ],
        ),
        migrations.AddField(
            model_name='documentdraft',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drafts', to='core.shareddocument'),
        ),
        migrations.CreateModel(
            name='DocumentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anchor', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(max_length=4000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.documentdraft')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.documentversion')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='core.shareddocument')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', '查看'), ('commenter', '评论'), ('editor', '创建修改稿'), ('reviewer', '审核')], default='viewer', max_length=12)),
                ('active', models.BooleanField(default=True)),
                ('membership_required', models.BooleanField(default=False)),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_access', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access', to='core.shareddocument')),
            ],
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependents', to='core.task')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='core.task')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_versions', to='core.submission')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.documentversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('submission', 'version'), name='submission_unique_document_version')],
            },
        ),
        migrations.CreateModel(
            name='DocumentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_id_used', models.PositiveBigIntegerField(null=True)),
                ('state', models.CharField(choices=[('new', '待生成'), ('running', '生成中'), ('ready', '待确认'), ('error', '未完成'), ('applied', '已创建')], default='new', max_length=12)),
                ('plan', models.JSONField(default=dict)),
                ('error', models.CharField(blank=True, max_length=1000)),
                ('call_id', models.UUIDField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_workspace', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace')),
                ('project', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plan_import', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='core.documentversion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('version', 'user'), name='document_one_plan_preview')],
            },
        ),
        migrations.AddConstraint(
            model_name='shareddocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('competition__isnull', True), ('project__isnull', True), ('task__isnull', True)), models.Q(('experiment__isnull', True), ('project__isnull', True), ('task__isnull', True)), models.Q(('competition__isnull', True), ('experiment__isnull', True), ('project__isnull', True)), models.Q(('competition__isnull', True), ('experiment__isnull', True), ('task__isnull', True)), _connector='OR'), name='document_one_context'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(fields=('document', 'number'), name='document_unique_version'),
        ),
        migrations.AddConstraint(
            model_name='documenteditrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('document', 'user'), name='document_pending_edit_request'),
        ),
        migrations.AddConstraint(
            model_name='documentdraft',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['draft', 'submitted', 'changes_requested'])), fields=('document', 'author'), name='document_one_open_draft'),
        ),
        migrations.AddConstraint(
            model_name='documentaccess',
            constraint=models.UniqueConstraint(fields=('document', 'user'), name='document_unique_access'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.UniqueConstraint(fields=('task', 'prerequisite'), name='task_unique_dependency'),
        ),
        migrations.AddConstraint(
            model_name='taskdependency',
            constraint=models.CheckConstraint(condition=models.Q(('task', models.F('prerequisite')), _negated=True), name='task_dependency_not_self'),
        ),
    ]
