# Generated by Django 5.2.17 on 2026-10-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_task_assignee_documentversion_documentdraft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentaccess',
            name='project_required',
            field=models.BooleanField(default=False),
        ),
    ]
