# Generated by Django 5.2.17 on 2026-10-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_documentaccess_project_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseclaim',
            name='settlement_kind',
            field=models.CharField(choices=[('cash', '现金报销'), ('api_quota', 'API 用量补发')], default='cash', max_length=12, verbose_name='补助方式'),
        ),
    ]
