# Generated by Django 5.2.17 on 2026-10-03 03:02

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0012_merge_desktop_and_main'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=160, verbose_name='模型 ID')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='显示名称（可选）')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('supports_tools', models.BooleanField(default=True, verbose_name='支持助手工具调用')),
                ('output_parameter', models.CharField(choices=[('max_tokens', 'max_tokens'), ('max_completion_tokens', 'max_completion_tokens')], default='max_tokens', max_length=24, verbose_name='输出上限参数')),
                ('max_output_tokens', models.PositiveIntegerField(default=2048, validators=[django.core.validators.MinValueValidator(64), django.core.validators.MaxValueValidator(8192)], verbose_name='最大输出 token')),
                ('price_feed_url', models.URLField(blank=True, verbose_name='每日价格 JSON 地址（可选）')),
                ('price_source', models.URLField(blank=True, verbose_name='价格依据网址（可选）')),
            ],
        ),
        migrations.CreateModel(
            name='PoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, default=200, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='团队每月额度（元）')),
                ('default_member_limit', models.DecimalField(decimal_places=2, default=50, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='成员默认每月额度（元）')),
                ('max_call_cost', models.DecimalField(decimal_places=2, default=10, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='单次调用最高预留（元）')),
                ('enabled', models.BooleanField(default=True, verbose_name='开放调用')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='厂商名称')),
                ('protocol', models.CharField(choices=[('openai', 'OpenAI 兼容'), ('anthropic', 'Anthropic Messages'), ('gemini', 'Gemini 原生')], default='openai', max_length=20, verbose_name='接口格式')),
                ('base_url', models.URLField(verbose_name='API 基础地址')),
                ('key_env', models.CharField(blank=True, max_length=120, verbose_name='密钥环境变量（可选）')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='每月额度（元）')),
                ('enabled', models.BooleanField(default=True, verbose_name='允许调用')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_allowance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AssistantJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(default='running', max_length=16)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('activity', models.JSONField(default=list)),
                ('result', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=60)),
                ('month', models.DateField()),
                ('spent', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('reserved', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'month'), name='pool_unique_month_budget')],
            },
        ),
        migrations.CreateModel(
            name='MemberToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80, verbose_name='凭证名称')),
                ('digest', models.CharField(max_length=64, unique=True)),
                ('prefix', models.CharField(max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriceVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField(verbose_name='生效时间')),
                ('input_rate', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='输入 / 百万 token')),
                ('output_rate', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='输出 / 百万 token')),
                ('cached_rate', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='缓存读取 / 百万 token')),
                ('cache_write_rate', models.DecimalField(decimal_places=6, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='缓存写入 / 百万 token')),
                ('currency', models.CharField(choices=[('CNY', 'CNY'), ('USD', 'USD')], default='CNY', max_length=3, verbose_name='币种')),
                ('cny_exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))], verbose_name='折算人民币汇率')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='价格来源')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prices', to='aihub.poolmodel')),
            ],
            options={
                'ordering': ['-effective_from', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('purpose', models.CharField(choices=[('api', 'API 调用'), ('assistant', 'AI 助手')], default='api', max_length=16)),
                ('status', models.CharField(choices=[('running', '调用中'), ('success', '已计量'), ('failed', '未计费失败'), ('unknown', '费用待核对')], default='running', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_write_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('reasoning_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('cost_cny', models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True)),
                ('reserved_cny', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('budget_month', models.DateField()),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('provider_request_id', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=60)),
                ('reconciled', models.BooleanField(default=False)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_calls', to='core.experiment')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='api_calls', to='core.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='api_calls', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aihub.poolmodel')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aihub.priceversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='poolmodel',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='aihub.provider'),
        ),
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.CharField(choices=[('verified', '来源已核对'), ('manual', '沿用管理员价格'), ('failed', '更新失败')], max_length=16)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_prices', to='aihub.poolmodel')),
                ('price', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='aihub.priceversion')),
            ],
            options={
                'ordering': ['-day', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('model', 'day'), name='pool_price_once_daily')],
            },
        ),
        migrations.AddConstraint(
            model_name='poolmodel',
            constraint=models.UniqueConstraint(fields=('provider', 'model_id'), name='pool_unique_provider_model'),
        ),
    ]
