# Generated by Django 5.2.17 on 2026-10-04 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0009_member_key_experiment'),
        ('core', '0019_avatars_conversation_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointGift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('transfer', '积分转账'), ('packet', '积分红包')], max_length=12)),
                ('mode', models.CharField(choices=[('equal', '均分'), ('random', '拼手气')], default='equal', max_length=12)),
                ('amount_cny', models.DecimalField(decimal_places=8, max_digits=18)),
                ('remaining_cny', models.DecimalField(decimal_places=8, max_digits=18)),
                ('count', models.PositiveIntegerField(default=1)),
                ('claimed_count', models.PositiveIntegerField(default=0)),
                ('greeting', models.CharField(default='科研顺利！', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_cny', models.DecimalField(decimal_places=8, default=0, max_digits=18)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='point_gift', to='core.chatmessage')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_point_gifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointGiftReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cny', models.DecimalField(decimal_places=8, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='aihub.pointgift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='point_gift_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='pointgift',
            constraint=models.CheckConstraint(condition=models.Q(('amount_cny__gt', 0), ('count__gte', 1), ('count__lte', 100), ('remaining_cny__gte', 0)), name='valid_point_gift'),
        ),
        migrations.AddConstraint(
            model_name='pointgiftreceipt',
            constraint=models.UniqueConstraint(fields=('gift', 'user'), name='one_point_gift_receipt'),
        ),
    ]
