# Generated by Django 5.2.17 on 2026-10-05 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0010_point_gifts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='call',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
