# Generated by Django 5.2.17 on 2026-10-05 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0011_alter_call_options'),
        ('core', '0020_experimentrun_sticker_alter_announcement_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assistantjob',
            index=models.Index(fields=['conversation', '-created_at', '-id'], name='assistant_job_recent'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['user', '-created_at', '-id'], name='call_user_recent'),
        ),
        migrations.AddIndex(
            model_name='call',
            index=models.Index(fields=['experiment', '-created_at', '-id'], name='call_experiment_recent'),
        ),
    ]
