# Generated by Django 5.2.17 on 2026-10-05 01:52

import django.db.models.deletion
from django.db import migrations, models


def preserve_existing_order(apps,schema_editor):
    job=apps.get_model('aihub','AssistantJob');order=apps.get_model('aihub','AssistantJobOrder')
    rows=job.objects.using(schema_editor.connection.alias).all()
    if schema_editor.connection.vendor=='sqlite':
        from django.db.models.expressions import RawSQL
        rows=rows.annotate(insertion=RawSQL('rowid',[])).order_by('created_at','insertion')
    else:rows=rows.order_by('created_at','pk')
    pending=[]
    for identifier in rows.values_list('pk',flat=True).iterator(chunk_size=1000):
        pending.append(order(job_id=identifier))
        if len(pending)==1000:
            order.objects.using(schema_editor.connection.alias).bulk_create(pending);pending=[]
    if pending:order.objects.using(schema_editor.connection.alias).bulk_create(pending)


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0012_assistantjob_assistant_job_recent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantJobOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_order', to='aihub.assistantjob')),
            ],
        ),
        migrations.RunPython(preserve_existing_order,migrations.RunPython.noop),
    ]
