# Generated by Django 5.2.17 on 2026-10-05 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0013_assistantjoborder'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetweek',
            name='base_limit_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='budgetweek',
            name='base_limit_snapshot',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=18, null=True),
        ),
    ]
