# Generated by Django 5.2.17 on 2026-10-05 18:06

import core.tenancy
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0015_assistant_images'),
        ('core', '0024_team_teammembership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantimage',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='assistantjoborder',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='membertoken',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='pointgrant',
            options={'base_manager_name': 'objects', 'default_manager_name': 'objects'},
        ),
        migrations.RemoveConstraint(
            model_name='budgetmonth',
            name='pool_unique_month_budget',
        ),
        migrations.RemoveConstraint(
            model_name='budgetweek',
            name='pool_unique_week_budget',
        ),
        migrations.AddField(
            model_name='allowance',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='apiratewindow',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='assistantimage',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='assistantjob',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='assistantjoborder',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='budgetmonth',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='budgetweek',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='call',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='membertoken',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='pointgift',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='pointgiftreceipt',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='pointgrant',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='poolmodel',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='priceversion',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddField(
            model_name='provider',
            name='team',
            field=models.ForeignKey(default=core.tenancy.required_team_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_allowances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='apiratewindow',
            name='scope',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=80, verbose_name='厂商名称'),
        ),
        migrations.AddConstraint(
            model_name='allowance',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='allowance_per_team'),
        ),
        migrations.AddConstraint(
            model_name='apiratewindow',
            constraint=models.UniqueConstraint(fields=('team', 'scope'), name='rate_scope_per_team'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('team', 'scope', 'month'), name='pool_unique_month_budget'),
        ),
        migrations.AddConstraint(
            model_name='budgetweek',
            constraint=models.UniqueConstraint(fields=('team', 'scope', 'week'), name='pool_unique_week_budget'),
        ),
        migrations.AddConstraint(
            model_name='poolsettings',
            constraint=models.UniqueConstraint(fields=('team',), name='pool_settings_per_team'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('team', 'name'), name='team_provider_name'),
        ),
    ]
