# Generated by Django 5.2.17 on 2026-10-06 09:10

import core.tenancy
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0016_alter_assistantimage_options_and_more'),
        ('core', '0030_platformaudit_workspace_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='allowance',
            name='allowance_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='apiratewindow',
            name='rate_scope_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='budgetmonth',
            name='pool_unique_month_budget',
        ),
        migrations.RemoveConstraint(
            model_name='budgetweek',
            name='pool_unique_week_budget',
        ),
        migrations.RemoveConstraint(
            model_name='poolsettings',
            name='pool_settings_per_team',
        ),
        migrations.RemoveConstraint(
            model_name='provider',
            name='team_provider_name',
        ),
        migrations.AddField(
            model_name='allowance',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='apiratewindow',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='assistantconversation',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='assistantimage',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='assistantjob',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='assistantjoborder',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='budgetmonth',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='budgetweek',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='call',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='membertoken',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='pointgift',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='pointgiftreceipt',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='pointgrant',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='poolmodel',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='poolsettings',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='priceversion',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AddField(
            model_name='provider',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='apiratewindow',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='assistantconversation',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='assistantimage',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='assistantjob',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='assistantjoborder',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='budgetmonth',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='budgetweek',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='call',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='membertoken',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='pointgift',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='pointgiftreceipt',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='pointgrant',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='poolmodel',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='poolsettings',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='priceversion',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='team',
            field=models.ForeignKey(blank=True, default=core.tenancy.team_id, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.team'),
        ),
        migrations.AddConstraint(
            model_name='allowance',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='allowance_per_team'),
        ),
        migrations.AddConstraint(
            model_name='apiratewindow',
            constraint=models.UniqueConstraint(fields=('workspace', 'scope'), name='rate_scope_per_team'),
        ),
        migrations.AddConstraint(
            model_name='budgetmonth',
            constraint=models.UniqueConstraint(fields=('workspace', 'scope', 'month'), name='pool_unique_month_budget'),
        ),
        migrations.AddConstraint(
            model_name='budgetweek',
            constraint=models.UniqueConstraint(fields=('workspace', 'scope', 'week'), name='pool_unique_week_budget'),
        ),
        migrations.AddConstraint(
            model_name='poolsettings',
            constraint=models.UniqueConstraint(fields=('workspace',), name='pool_settings_per_team'),
        ),
        migrations.AddConstraint(
            model_name='provider',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='team_provider_name'),
        ),
    ]
