# Generated by Django 5.2.17 on 2026-10-06 09:21

import core.tenancy
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihub', '0017_remove_allowance_allowance_per_team_and_more'),
        ('core', '0032_alter_announcement_workspace_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowance',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='apiratewindow',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='assistantconversation',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='assistantimage',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='assistantjob',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='assistantjoborder',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='budgetmonth',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='budgetweek',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='call',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='dailyprice',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='membertoken',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='pointgift',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='pointgiftreceipt',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='pointgrant',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='poolmodel',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='poolsettings',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='priceversion',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='workspace',
            field=models.ForeignKey(default=core.tenancy.required_workspace_id, editable=False, on_delete=django.db.models.deletion.PROTECT, to='core.workspace'),
        ),
    ]
