from . import resource_tree, talent, project_cooperation, personal_area
from django.urls import include, path
from . import local_chat_delivery

from . import views, portal, messages, competitions, chat_references, recovery, experiment_runs, social, releases, member_management
from .desktop_api import desktop_api
from . import documents, document_planning, office_documents
from .avatars import member_avatar
from . import teams, recruitment, personal_messages
from . import account_registration, account_lifecycle, message_teams, account_notices
from aihub import gifts

urlpatterns = [
    path("messages/local-records/ack/", local_chat_delivery.acknowledge, name="local_chat_ack"),
    path("messages/local-records/state/", local_chat_delivery.state, name="local_chat_state"),
    path('documents/', documents.index, name='documents'),
    path('documents/new/', documents.create, name='document_new'),
    path('documents/members/', document_planning.members, name='document_plan_members'),
    path('documents/office/file/', office_documents.file, name='office_file'),
    path('documents/office/callback/<uuid:key>/', office_documents.callback, name='office_callback'),
    path('documents/plans/<uuid:plan_id>/', document_planning.status, name='document_plan_status'),
    path('documents/plans/<uuid:plan_id>/apply/', document_planning.apply, name='document_plan_apply'),
    path('documents/<int:pk>/', documents.detail, name='document_detail'),
    path('documents/<int:pk>/action/', documents.action, name='document_action'),
    path('documents/<int:pk>/state/', documents.state, name='document_state'),
    path('documents/<int:pk>/file/', documents.file, name='document_file'),
    path('documents/<int:pk>/images/', documents.image_upload, name='document_image_upload'),
    path('documents/<int:pk>/images/<int:image_pk>/', documents.image, name='document_image'),
    path('documents/<int:pk>/drafts/<int:draft_pk>/save/', documents.save, name='document_save'),
    path('documents/<int:pk>/drafts/<int:draft_pk>/review/', documents.review, name='document_review'),
    path('documents/<int:pk>/comments/', documents.comment, name='document_comment'),
    path('documents/<int:pk>/office/', office_documents.config, name='office_config'),
    path('documents/<int:pk>/drafts/<int:draft_pk>/office-save/', office_documents.force_save, name='office_force_save'),
    path('documents/<int:pk>/plan/', document_planning.preview, name='document_plan'),
    path('documents/<int:pk>/plan/generate/', document_planning.generate, name='document_plan_generate'),
    path('me/', personal_area.home, name='me_home'),
    path('me/api/', personal_area.api, name='me_api'),
    path('me/usage/', personal_area.usage, name='me_usage'),
    path('me/connections/', personal_area.connections, name='me_connections'),
    path('me/ledger/', personal_area.ledger, name='me_ledger'),
    path('me/ledger/new/', personal_area.ledger, name='me_ledger_new'),
    path('me/ledger/<int:pk>/edit/', personal_area.ledger, name='me_ledger_edit'),
    path('me/ledger/<int:pk>/archive/', personal_area.ledger, name='me_ledger_archive'),
    path('finance/teams/', personal_area.team_finance, name='finance_teams'),
    path('projects/<int:pk>/cooperation/revoke/',project_cooperation.revoke,name='project_cooperation_revoke'),
    path('discover/', recruitment.square, name='discover'),
    path('discover/talents/', talent.market, name='talent_market'),
    path('discover/talents/<int:pk>/', talent.detail, name='talent_detail'),
    path('me/talent/', talent.profile, name='talent_profile'),
    path('discover/profile/', talent.legacy_profile, name='legacy_talent_profile'),
    path('discover/applications/', recruitment.applications, name='discover_applications'),
    path('discover/offers/', talent.offers, name='talent_offers'),
    path('discover/offers/<int:pk>/', talent.offer_detail, name='talent_offer'),
    path('discover/offers/<int:pk>/respond/', talent.respond, name='talent_offer_respond'),
    path('workspace/navigation/<int:pk>/',resource_tree.branch,name='resource_branch'),
    path('messages/notices/',account_notices.inbox,name='account_notices'),
    path('messages/notices/<int:pk>/read/',account_notices.read,name='account_notice_read'),
    path('account/close/',account_lifecycle.close,name='account_close'),
    path('account/export/',account_lifecycle.export,name='account_export'),
    path('platform/audit/',account_lifecycle.platform_audit,name='platform_audit'),
    path('platform/accounts/',account_lifecycle.platform_accounts,name='platform_accounts'),
    path('platform/accounts/<int:pk>/reset-password/',account_lifecycle.reset_password,name='platform_reset_password'),
    path('messages/teams/',message_teams.index,name='messages_teams'),
    path('messages/teams/rename/',message_teams.rename,name='messages_team_rename'),
    path('messages/teams/transfer/',message_teams.transfer,name='messages_team_transfer'),
    path('messages/teams/leave/',message_teams.leave,name='messages_team_leave'),
    path('messages/teams/disband/',message_teams.disband,name='messages_team_disband'),
    path('messages/teams/members/<int:pk>/remove/',message_teams.remove_member,name='messages_team_remove'),
    path('messages/teams/review/',message_teams.review,name='messages_team_review'),
    path('messages/teams/members/',message_teams.members,name='messages_team_members'),
    path('messages/teams/invites/',message_teams.invites,name='messages_team_invites'),
    path('messages/teams/recruitment/',message_teams.recruitment,name='messages_team_recruitment'),
    path('messages/teams/permissions/<int:pk>/',message_teams.permissions,name='messages_team_permissions'),
    path('messages/files/<int:pk>/',personal_messages.upload_file,name='personal_message_file'),
    path('messages/legacy-files/<int:pk>/',personal_messages.legacy_file,name='personal_legacy_file'),
    path('messages/personal/<int:pk>/action/<int:message_pk>/',personal_messages.personal_action,name='personal_message_action'),
    path('messages/personal/<int:pk>/settings/',personal_messages.thread_settings,name='personal_thread_settings'),
    path('messages/personal/<int:pk>/history/',personal_messages.thread_history,name='personal_thread_history'),
    path('messages/groups/<int:pk>/settings/',personal_messages.thread_settings,{'is_group':True},name='group_thread_settings'),
    path('messages/groups/<int:pk>/history/',personal_messages.thread_history,{'is_group':True},name='group_thread_history'),
    path('messages/groups/<int:pk>/action/<int:message_pk>/',personal_messages.group_action,name='group_message_action'),
    path('account/register/', account_registration.register, name='account_register'),
    path('teams/', teams.index, name='teams'),
    path('teams/create/', teams.create, name='team_create'),
    path('teams/switch/', teams.switch, name='team_switch'),
    path('teams/join/', teams.join, name='team_join'),
    path('teams/transfer/', teams.transfer, name='team_transfer'),
    path('teams/rename/', teams.rename, name='team_rename'),
    path('teams/leave/', teams.leave, name='team_leave'),
    path('teams/disband/', teams.disband, name='team_disband'),
    path('team-square/', recruitment.square, name='team_square'),
    path('team-square/<int:pk>/', recruitment.detail, name='team_listing'),
    path('team-square/apply/<int:pk>/', recruitment.apply, name='team_apply'),
    path('team-square/resume/', recruitment.resume, name='applicant_resume'),
    path('team-square/applications/', recruitment.applications, name='my_applications'),
    path('team-square/applications/<int:pk>/', recruitment.application_action, name='team_application_action'),
    path('manage/recruitment/', recruitment.manage, name='recruitment_manage'),
    path('manage/recruitment/applications/', recruitment.review, name='team_application_review'),
    path('teams/permissions/<int:pk>/', teams.member_permissions, name='team_member_permissions'),
    path('platform/', teams.platform, name='platform'),
    path('desktop/api/<str:action>/', desktop_api, name='desktop_api'),
    path('updates/current/', releases.current, name='release_current'),
    path('updates/', releases.notices, name='application_updates'),
    path('updates/<int:pk>/', releases.notices, name='application_update_detail'),
    path('download/', portal.download, name='public_download'),
    path('competitions/', competitions.index, name='competitions'),
    path('competitions/new/', competitions.edit, name='competition_new'),
    path('competitions/<int:pk>/', competitions.detail, name='competition_detail'),
    path('competitions/<int:pk>/edit/', competitions.edit, name='competition_edit'),
    path('competitions/<int:pk>/archive/', competitions.archive, name='competition_archive'),
    path('messages/social/', personal_messages.index, name='messages_social'),
    path('messages/friends/request/', personal_messages.request_friend, name='request_friend'),
    path('messages/friends/search/', personal_messages.search_friend, name='friend_search'),
    path('messages/friends/<int:pk>/', personal_messages.friend_action, name='friend_action'),
    path('messages/personal/<int:pk>/', personal_messages.personal, name='personal_chat'),
    path('messages/groups/create/', personal_messages.create_group, name='group_create'),
    path('messages/groups/<int:pk>/', personal_messages.group_chat, name='group_chat'),
    path('messages/groups/<int:pk>/manage/', personal_messages.manage_group, name='group_manage'),
    path('messages/', messages.hub, name='messages_hub'),
    path('messages/poll/', messages.poll, name='messages_poll'),
    path('messages/unread/', messages.unread, name='messages_unread'),
    path('messages/read/', messages.read, name='messages_read'),
    path('messages/manage/', messages.manage, name='messages_manage'),
    path('messages/history/', messages.search_history, name='messages_history'),
    path('members/<int:pk>/card/', social.member, name='member_card'),
    path('members/<int:pk>/reset-password/', member_management.reset_password, name='member_reset_password'),
    path('members/<int:pk>/delete/', member_management.delete_account, name='member_delete'),
    path('account/set-password/', member_management.set_password, name='required_password_change'),
    path('messages/stickers/', social.stickers, name='stickers'),
    path('messages/stickers/<int:pk>/file/', social.sticker_file, name='sticker_file'),
    path('messages/points/', gifts.wallet, name='point_wallet'),
    path('messages/points/send/', gifts.send, name='point_gift_send'),
    path('messages/points/<uuid:pk>/', gifts.detail, name='point_gift_detail'),
    path('messages/points/<uuid:pk>/claim/', gifts.claim, name='point_gift_claim'),
    path('messages/<int:pk>/action/', messages.message_action, name='message_action'),
    path('messages/references/search/', chat_references.search, name='chat_reference_search'),
    path('messages/references/<str:kind>/<int:pk>/', chat_references.detail, name='chat_reference_detail'),
    path('messages/to/<int:peer_pk>/', messages.hub, name='messages_private'),
    path('messages/to/<int:peer_pk>/poll/', messages.poll, name='messages_private_poll'),
    path('public/experiment-files/<int:pk>/', portal.public_experiment_file, name='public_experiment_file'),
    path('workspace/', portal.workspace_home, name='workspace_home'),
    path('sampling/', include('sampling.urls')),
    path('public/projects/', portal.public_projects, name='public_projects'),
    path('public/projects/<int:pk>/', portal.public_project_detail, name='public_project_detail'),
    path('public/experiments/', portal.public_experiments, name='public_experiments'),
    path('public/experiments/<int:pk>/', portal.public_experiment_detail, name='public_experiment_detail'),
    path('public/members/', portal.public_members, name='public_members'),
    path('contact/', portal.public_members, name='contact'),  # 与成员公开信息合并为同一页
    path('manage/contact/', portal.contact_edit, name='contact_edit'),
    path('workspace/announcements/new/', portal.announcement_edit, name='announcement_new'),
    path('workspace/announcements/<int:pk>/edit/', portal.announcement_edit, name='announcement_edit'),
    path('experiments/', portal.experiments, name='experiments'),
    path('experiments/new/', portal.experiment_edit, name='experiment_new'),
    path('experiments/compare/', portal.experiments_compare, name='experiments_compare'),
    path('experiments/templates/<int:pk>/delete/', portal.experiment_template_delete, name='experiment_template_delete'),
    path('experiments/<int:pk>/', portal.experiment_detail, name='experiment_detail'),
    path('experiments/<int:pk>/edit/', portal.experiment_edit, name='experiment_edit'),
    path('experiments/<int:pk>/runs/new/', experiment_runs.edit, name='experiment_run_new'),
    path('experiments/<int:pk>/runs/<int:run_pk>/edit/', experiment_runs.edit, name='experiment_run_edit'),
    path('experiments/<int:pk>/visibility/', portal.experiment_visibility, name='experiment_visibility'),
    path('projects/<int:pk>/visibility/', portal.project_visibility, name='project_visibility'),
    path('account/public/', portal.public_profile_edit, name='public_profile_edit'),
    path('recycle-bin/', portal.recycle_bin, name='recycle_bin'),
    path('recycle-bin/<str:kind>/<int:pk>/restore/', portal.restore, name='restore'),
    path('recycle-bin/<str:kind>/<int:pk>/delete/', portal.permanently_delete, name='permanently_delete'),

    path('', portal.public_home, name='public_home'),
    path('projects/', views.dashboard, name='dashboard'),

    # 项目展示 · 关于 · 聊天室
    path('showcase/', portal.public_projects, name='showcase'),
    path('about/', portal.public_members, name='about'),
    path('chat/', views.chat, name='chat'),
    path('chat/public/', views.chat_public, name='chat_public'),
    path('chat/public/messages/', views.chat_public_messages, name='chat_public_messages'),
    path('chat/developers/', views.chat_developers, name='chat_developers'),
    path('chat/developers/messages/', views.chat_developers_messages, name='chat_developers_messages'),

    # 登录（先选身份：管理员／开发者／普通用户）
    path('login/', views.RoleLoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),

    # 忘记密码：邮箱自助找回。URL 名沿用 Django 约定，令牌与邮件模板都依赖它们。
    path('account/forgot/', recovery.recover, name='password_reset'),
    path('account/forgot/sent/', recovery.legacy_code, name='password_reset_done'),
    path('account/reset/<uidb64>/<token>/', views.ResetPasswordConfirmView.as_view(),
         name='password_reset_confirm'),
    path('account/reset/done/', views.ResetPasswordCompleteView.as_view(), name='password_reset_complete'),

    # 个人中心：资料、角色权限与修改密码（旧改密链接跳到同一页）
    path('account/', views.profile, name='profile'),
    path('accounts/<int:pk>/avatar/<str:version>/', member_avatar, name='member_avatar'),
    path('account/password/', views.change_password, name='change_password'),

    # 已登录但忘了当前密码：邮箱验证码验证身份后重置（先验证码，再设新密码）
    path('account/forgot-code/', recovery.legacy_code, name='password_code_reset'),
    path('account/forgot-code/send/', recovery.legacy_code, name='password_code_send'),
    path('account/forgot-code/new-password/', recovery.legacy_code,
         name='password_code_new_password'),

    # 项目（项目 → 母任务 → 子任务）
    path('projects/new/', views.project_edit, name='project_new'),
    path('projects/<int:pk>/', views.project_detail, name='project_detail'),
    path('projects/<int:pk>/edit/', views.project_edit, name='project_edit'),
    path('projects/<int:pk>/close/', views.project_close, name='project_close'),
    path('projects/<int:pk>/archive/', views.project_archive, name='project_archive'),
    path('projects/<int:pk>/submit/', views.project_submit, name='project_submit'),
    path('projects/<int:pk>/comment/', views.project_comment, name='project_comment'),

    # 任务
    path('tasks/', views.task_list, name='task_list'),
    path('tasks/new/', views.task_edit, name='task_new'),
    path('tasks/<int:pk>/', views.task_detail, name='task_detail'),
    path('tasks/<int:pk>/edit/', views.task_edit, name='task_edit'),
    path('tasks/<int:pk>/progress/', views.task_progress, name='task_progress'),
    path('tasks/<int:pk>/submit/', views.task_submit, name='task_submit'),
    path('tasks/<int:pk>/comment/', views.task_comment, name='task_comment'),
    path('tasks/<int:pk>/close/', views.task_close, name='task_close'),
    path('tasks/<int:pk>/archive/', views.task_archive, name='task_archive'),

    # 成果与附件
    path('submissions/<int:pk>/review/', views.submission_review, name='submission_review'),
    path('submissions/<int:pk>/final/', views.submission_final, name='submission_final'),
    path('submissions/<int:pk>/comment/', views.submission_comment, name='submission_comment'),
    path('attachments/<int:pk>/download/', views.attachment_download, name='attachment_download'),

    # 人员：邀请码与成员任免
    path('manage/', views.team_manage, name='team_manage'),
    path('manage/invites/', views.invites, name='invites'),
    path('manage/members/', views.members, name='members'),

    # 财务：报销申请与团队账本合并在一页（旧报销链接跳到同一页的报销区）
    path('finance/', views.finance_list, name='finance_list'),
    path('finance/new/', views.finance_edit, name='finance_new'),
    path('finance/<int:pk>/edit/', views.finance_edit, name='finance_edit'),
    path('finance/<int:pk>/void/', views.finance_void, name='finance_void'),
    path('finance/<int:pk>/delete/', views.finance_archive, name='finance_archive'),
    path('claims/<int:pk>/delete/', views.claim_archive, name='claim_archive'),
    path('finance/claims/', views.claim_list, name='claim_list'),
    path('finance/claims/new/', views.claim_new, name='claim_new'),
    path('finance/claims/<int:pk>/review/', views.claim_review, name='claim_review'),
]
