# Generated by Django 5.2.17 on 2026-10-06 09:09

import django.db.models.deletion
import sampling.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_emailverificationcode'),
        ('sampling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='samplingrun',
            name='source_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='sampling.samplingrun', verbose_name='来源版本'),
        ),
        migrations.AlterField(
            model_name='samplingartifact',
            name='artifact_type',
            field=models.CharField(choices=[('frame', '抽样框'), ('registry', '候选池'), ('protocol', '抽样协议'), ('certificate', '逐样本抽样凭证'), ('ranking', '候选池完整排序'), ('selected', '已抽选样本'), ('reserve', '备用样本'), ('issues', '抽样问题'), ('download_queue', 'PDF下载任务'), ('evidence_queue', '证据补全任务'), ('bundle', '完整结果包'), ('protocol_md', '抽样协议说明'), ('safe_manifest', '样本编号清单'), ('labels_seed', '真实标签种子表')], max_length=40),
        ),
        migrations.AlterField(
            model_name='samplingrun',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sampling_runs', to='core.project', verbose_name='关联项目'),
        ),
        migrations.CreateModel(
            name='SamplingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255, verbose_name='原 PDF 文件名')),
                ('pdf_file', models.FileField(upload_to=sampling.models.document_upload_to)),
                ('pdf_sha256', models.CharField(max_length=64)),
                ('md_file', models.FileField(blank=True, upload_to=sampling.models.document_upload_to)),
                ('md_sha256', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('received', 'PDF 已接收'), ('queued', '等待转换'), ('running', '正在转换'), ('ready', '转换完成'), ('review', '需人工检查'), ('failed', '转换失败')], default='received', max_length=20)),
                ('pages', models.PositiveIntegerField(default=0)),
                ('characters', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('converter_version', models.CharField(blank=True, max_length=80)),
                ('claim_token', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='sampling.candidatepaper')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='sampling_document_queue')],
                'constraints': [models.UniqueConstraint(fields=('candidate', 'pdf_sha256'), name='sampling_unique_pdf')],
            },
        ),
    ]
