# Generated by Django 5.2.17 on 2026-10-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampling', '0002_samplingrun_source_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatepaper',
            name='cross_disciplinary_journal',
            field=models.BooleanField(default=False),
        ),
    ]
