const { contextBridge, ipcRenderer } = require('electron');
const invoke = (name, ...args) => ipcRenderer.invoke(name, ...args);
contextBridge.exposeInMainWorld('desktop', {
  info: () => invoke('desktop:info'),
  presentationReady: generation=>invoke('desktop:presentation-ready',generation),
  accountReady: generation=>invoke('desktop:account-ready',generation),
  retryLoading: ()=>invoke('desktop:loading-retry'),
  dismissLoading: ()=>invoke('desktop:loading-dismiss'),
  connection: () => invoke('connection:get'),
  saveConnection: value => invoke('connection:save',value),
  updateFeature:index=>invoke('updates:feature',index),
  onUpdateOpen:callback=>ipcRenderer.on('desktop:update-open',()=>callback()),
  showUpdateInfo:()=>invoke('updates:show'),
  updates: () => invoke('updates:status'),
  checkUpdates: () => invoke('updates:check'),
  downloadUpdate: () => invoke('updates:download'),
  installUpdate: () => invoke('updates:install'),
  onUpdates: callback => ipcRenderer.on('desktop:updates',(_,value)=>callback(value)),
  authStatus: () => invoke('auth:status'),
  login: value => invoke('auth:login',value),
  register: value => invoke('auth:register',value),
  setupAccount: value => invoke('auth:setup',value),
  forgotPassword: () => invoke('auth:forgot-password'),
  logout: () => invoke('auth:logout'),
  navigate: name => invoke('desktop:navigate', name),
  navigateWorkspace: path=>invoke('desktop:workspace-navigate',path),
  collapseWorkspace: (value,reduced)=>invoke('desktop:workspace-collapse',value,reduced),
  window: action => invoke('desktop:window', action),
  account: () => invoke('desktop:account'),
  usage: () => invoke('desktop:usage'),
  usageOpen: () => invoke('desktop:usage-open'),
  accountMenu: open => invoke('desktop:account-menu', open),
  repoChoose: initialize => invoke('repo:choose',initialize),
  repoList: ()=>invoke('repo:list'),repoSelect: directory=>invoke('repo:select',directory),repoRemove: (directory,physical)=>invoke('repo:remove',directory,physical),repoNewFile: ()=>invoke('repo:new-file'),
  repoStatus: () => invoke('repo:status'),
  repoDiff: file => invoke('repo:diff', file),
  repoFiles: () => invoke('repo:files'),
  repoRead: file => invoke('repo:read',file),
  repoSave: value => invoke('repo:save',value),
  repoCreate: (file,context) => invoke('repo:create',file,context),
  repoSearch: (query,context) => invoke('repo:search',query,context),
  repoHistory: () => invoke('repo:history'),
  repoLeave: () => invoke('repo:leave'),
  repoDraft: value => invoke('repo:draft',value),
  repoPerform: (action,value) => invoke('repo:perform',action,value),
  repoOpen: file => invoke('repo:open',file),
  onRepositorySaved: callback => ipcRenderer.on('repo:saved',(_,value) => callback(value)),
  onRepositoryDiscard: callback => ipcRenderer.on('repo:discard',callback),
  browserAction:(action,url)=>invoke('desktop:browser-action',action,url),onBrowser:callback=>ipcRenderer.on('desktop:browser',(_,value)=>callback(value)),
  openExternal: url => invoke('desktop:external', url),
  settings: () => invoke('settings:get'),
  saveSettings: value => invoke('settings:save', value),
  appearance: () => invoke('appearance:get'),
  saveAppearance: value => invoke('appearance:save',value),
  chooseWallpaper: () => invoke('appearance:wallpaper'),
  clearWallpaper: () => invoke('appearance:clear'),
  resetAppearance: () => invoke('appearance:reset'),
  onAppearance: callback => ipcRenderer.on('desktop:appearance',(_,value)=>callback(value)),
  onState: callback => {
    const listener = (_, value) => callback(value);
    ipcRenderer.on('desktop:state', listener);
    return () => ipcRenderer.removeListener('desktop:state', listener);
  }
});
