const {WebContentsView,BrowserWindow}=require('electron');
const {applicationIcon,configureWindowIdentity}=require('./app-icon.cjs');
const path=require('node:path');
const dns=require('node:dns').promises,net=require('node:net');
const {randomUUID}=require('node:crypto');
function publicAddress(value){if(net.isIP(value)===4){const [a,b]=value.split('.').map(Number);return a>0&&a<224&&![10,127].includes(a)&&!(a===100&&b>=64&&b<=127)&&!(a===169&&b===254)&&!(a===172&&b>=16&&b<=31)&&!(a===192&&(b===168||b===0||b===2))&&!(a===198&&(b===18||b===19||b===51))&&!(a===203&&b===0);}if(net.isIP(value)===6)return /^2[0-9a-f]{3}:/i.test(value)&&!/^2001:(db8|0):/i.test(value);return false;}
// This isolated browser has no workspace IPC/cookies. A domain mapped to the
// 198.18/15 TUN proxy range is allowed; literal reserved IP URLs remain blocked.
// The privileged server reader separately pins real public IPs on every hop.
function address(url){if(typeof url!=='string'||url.length>3000||/[\x00-\x1f]/.test(url))throw Error('网页地址无效。');const target=new URL(url);if(!['http:','https:'].includes(target.protocol)||target.username||target.password||target.port&&!['80','443'].includes(target.port))throw Error('只支持公开网页。');const host=target.hostname.replace(/^\[|\]$/g,'').toLowerCase().replace(/\.$/,'');if(net.isIP(host)?!publicAddress(host):(!host.includes('.')||/(^|\.)(localhost|local|internal|home|lan)$/.test(host)))throw Error('不能打开本机或内网网页。');return target;}
function safeUserAgent(value){return String(value||'Zhiyu').replace(/[^\x20-\x7e]+/g,'Zhiyu');}
class PublicBrowser{
  constructor(window,changed){this.window=window;this.changed=changed;this.visible=false;this.view=new WebContentsView({webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,partition:'public-web-reader-'+randomUUID(),webSecurity:true}});window.contentView.addChildView(this.view);this.view.setVisible(false);const wc=this.view.webContents;this.contents=wc;wc.setUserAgent(safeUserAgent(wc.getUserAgent()));wc.session.setPermissionRequestHandler((_web,_permission,callback)=>callback(false));wc.session.setPermissionCheckHandler(()=>false);wc.session.on('will-download',event=>event.preventDefault());wc.setWindowOpenHandler(({url})=>{try{const target=address(url);setImmediate(()=>{if(!wc.isDestroyed())wc.loadURL(target.href).catch(()=>{});});}catch(_){}return {action:'deny'};});wc.session.webRequest.onBeforeRequest((details,callback)=>{(async()=>{if(details.url.startsWith('data:')||details.url.startsWith('blob:')){callback({cancel:false});return;}const url=address(details.url);const host=url.hostname.replace(/^\[|\]$/g,'');const values=net.isIP(host)?[{address:host}]:await dns.lookup(host,{all:true});callback({cancel:!values.length||values.some(value=>!publicAddress(value.address) && !(!net.isIP(host) && /^198\.(18|19)\./.test(value.address)))});})().catch(()=>callback({cancel:true}));});wc.on('will-navigate',(event,url)=>{try{address(url);}catch(_){event.preventDefault();}});const navigated=()=>{this.requested=wc.getURL();this.publish('');};wc.on('did-navigate',navigated);wc.on('did-navigate-in-page',navigated);wc.on('did-start-loading',()=>this.publish());wc.on('did-stop-loading',()=>this.publish());wc.on('page-title-updated',()=>this.publish());wc.on('did-fail-load',(_event,code,_message,_url,isMainFrame)=>{if(code!==-3&&isMainFrame)this.publish('网页未能打开，可刷新或在外部浏览器打开。');});}
  snapshot(){const wc=this.contents;if(this.disposing||wc.isDestroyed())return {visible:false,mode:'sidebar',url:this.requested||'',title:'',loading:false,canBack:false,canForward:false,zoom:1,error:''};return {visible:this.visible,hideComposer:Boolean(this.hideComposer),mode:this.mode||'sidebar',url:this.error?this.requested:wc.getURL()||this.requested||'',title:wc.getTitle(),loading:wc.isLoading(),canBack:wc.navigationHistory.canGoBack(),canForward:wc.navigationHistory.canGoForward(),zoom:wc.getZoomFactor(),error:this.error||''};}
  publish(error){if(this.disposing||this.contents.isDestroyed())return;if(error!==undefined)this.error=error;const value=this.snapshot();if(this.floating&&!this.floating.isDestroyed())this.floating.webContents.send('public-browser:state',value);this.changed(value);}
  async open(url){if(this.disposing||this.contents.isDestroyed())throw Error('浏览器已关闭。');const target=address(url);this.requested=target.href;this.error='';this.visible=true;this.publish();await this.contents.loadURL(target.href).catch(()=>{});}
  action(name){const wc=this.contents;if(this.disposing||wc.isDestroyed())return;if(name==='close'){if(this.mode==='window')this.dock(false);this.visible=false;wc.stop();}else if(name==='back'&&wc.navigationHistory.canGoBack())wc.navigationHistory.goBack();else if(name==='forward'&&wc.navigationHistory.canGoForward())wc.navigationHistory.goForward();else if(name==='reload'){if(this.error){this.error='';wc.loadURL(this.requested||wc.getURL()).catch(()=>{});}else wc.reload();}else if(name==='expand'){if(this.mode==='window')this.dock();this.mode=this.mode==='expanded'?'sidebar':'expanded';}else if(name==='detach')this.detach();else if(name==='dock'){if(this.mode==='window')this.dock();else this.mode='sidebar';}else if(name==='toggle-composer')this.hideComposer=!this.hideComposer;else if(name==='zoom-in')wc.setZoomFactor(Math.min(2.5,wc.getZoomFactor()+.1));else if(name==='zoom-out')wc.setZoomFactor(Math.max(.5,wc.getZoomFactor()-.1));else if(name==='zoom-reset')wc.setZoomFactor(1);this.publish();}
  detach(){if(this.disposing||this.contents.isDestroyed())return;if(this.floating&&!this.floating.isDestroyed()){this.floating.show();this.floating.focus();return;}this.mode='window';this.window.contentView.removeChildView(this.view);const floating=new BrowserWindow({width:1100,height:800,minWidth:600,minHeight:400,show:false,icon:applicationIcon(),title:'网页浏览器',autoHideMenuBar:true,webPreferences:{preload:path.join(__dirname,'public-browser-preload.cjs'),sandbox:true,contextIsolation:true,nodeIntegration:false}});configureWindowIdentity(floating);this.floating=floating;floating.contentView.addChildView(this.view);const resize=()=>{if(this.disposing||this.floating!==floating||floating.isDestroyed()||this.contents.isDestroyed())return;const [width,height]=floating.getContentSize();this.view.setBounds({x:0,y:76,width,height:Math.max(1,height-76)});this.view.setVisible(this.visible);};floating.on('resize',resize);floating.on('close',event=>{if(this.disposing)return;event.preventDefault();this.dock(false);this.publish();});floating.webContents.setWindowOpenHandler(()=>({action:'deny'}));floating.webContents.on('will-navigate',event=>event.preventDefault());floating.loadFile(path.join(__dirname,'ui/browser.html')).then(()=>{if(!this.disposing&&this.floating===floating&&!floating.isDestroyed()){resize();this.publish();floating.show();}}).catch(error=>{if(this.disposing||this.floating!==floating||floating.isDestroyed()||error.code==='ERR_ABORTED'||error.errno===-3)return;this.dock();this.publish('独立浏览器未能打开，请重试。');});resize();}
  dock(visible=true){if(this.disposing||this.contents.isDestroyed())return;const floating=this.floating;if(floating&&!floating.isDestroyed())floating.contentView.removeChildView(this.view);this.floating=null;this.window.contentView.addChildView(this.view);this.mode='sidebar';this.visible=visible;if(floating&&!floating.isDestroyed())floating.destroy();}
  dispose(){if(this.disposing)return;this.disposing=true;this.visible=false;const floating=this.floating;if(floating&&!floating.isDestroyed()){floating.contentView.removeChildView(this.view);floating.destroy();}else if(!this.window.isDestroyed())this.window.contentView.removeChildView(this.view);this.floating=null;if(!this.contents.isDestroyed()){this.contents.session.clearStorageData().catch(()=>{});this.contents.close();}}
}
module.exports={PublicBrowser,publicAddress,address,safeUserAgent};
