const {WebContentsView}=require('electron');
const dns=require('node:dns').promises,net=require('node:net');
function publicAddress(value){if(net.isIP(value)===4){const [a,b]=value.split('.').map(Number);return a>0&&a<224&&![10,127].includes(a)&&!(a===100&&b>=64&&b<=127)&&!(a===169&&b===254)&&!(a===172&&b>=16&&b<=31)&&!(a===192&&(b===168||b===0||b===2))&&!(a===198&&(b===18||b===19||b===51))&&!(a===203&&b===0);}if(net.isIP(value)===6)return /^2[0-9a-f]{3}:/i.test(value)&&!/^2001:(db8|0):/i.test(value);return false;}
// This isolated browser has no workspace IPC/cookies. A domain mapped to the
// 198.18/15 TUN proxy range is allowed; literal reserved IP URLs remain blocked.
// The privileged server reader separately pins real public IPs on every hop.
function address(url){if(typeof url!=='string'||url.length>3000||/[\x00-\x1f]/.test(url))throw Error('网页地址无效。');const target=new URL(url);if(!['http:','https:'].includes(target.protocol)||target.username||target.password||target.port&&!['80','443'].includes(target.port))throw Error('只支持公开网页。');const host=target.hostname.replace(/^\[|\]$/g,'').toLowerCase().replace(/\.$/,'');if(net.isIP(host)?!publicAddress(host):(!host.includes('.')||/(^|\.)(localhost|local|internal|home|lan)$/.test(host)))throw Error('不能打开本机或内网网页。');return target;}
class PublicBrowser{
  constructor(window,changed){this.window=window;this.changed=changed;this.visible=false;this.view=new WebContentsView({webPreferences:{sandbox:true,contextIsolation:true,nodeIntegration:false,partition:'public-web-reader',webSecurity:true}});window.contentView.addChildView(this.view);this.view.setVisible(false);const wc=this.view.webContents;wc.session.setPermissionRequestHandler((_web,_permission,callback)=>callback(false));wc.session.setPermissionCheckHandler(()=>false);wc.session.on('will-download',event=>event.preventDefault());wc.setWindowOpenHandler(()=>({action:'deny'}));wc.session.webRequest.onBeforeRequest((details,callback)=>{(async()=>{if(details.url.startsWith('data:')||details.url.startsWith('blob:')){callback({cancel:false});return;}const url=address(details.url);const host=url.hostname.replace(/^\[|\]$/g,'');const values=net.isIP(host)?[{address:host}]:await dns.lookup(host,{all:true});callback({cancel:!values.length||values.some(value=>!publicAddress(value.address) && !(!net.isIP(host) && /^198\.(18|19)\./.test(value.address)))});})().catch(()=>callback({cancel:true}));});wc.on('will-navigate',(event,url)=>{try{address(url);}catch(_){event.preventDefault();}});wc.on('did-navigate',()=>this.publish());wc.on('did-navigate-in-page',()=>this.publish());wc.on('did-start-loading',()=>this.publish());wc.on('did-stop-loading',()=>this.publish());wc.on('page-title-updated',()=>this.publish());wc.on('did-fail-load',(_event,code,message)=>{if(code!==-3)this.publish('网页未能打开，可刷新或在外部浏览器打开。');});}
  snapshot(){const wc=this.view.webContents;return {visible:this.visible,url:this.error?this.requested:wc.getURL()||this.requested||'',title:wc.getTitle(),loading:wc.isLoading(),canBack:wc.navigationHistory.canGoBack(),error:this.error||''};}
  publish(error){if(error!==undefined)this.error=error;this.changed(this.snapshot());}
  async open(url){const target=address(url);this.requested=target.href;this.error='';this.visible=true;this.publish();await this.view.webContents.loadURL(target.href).catch(()=>{});}
  action(name){const wc=this.view.webContents;if(name==='close'){this.visible=false;wc.stop();}else if(name==='back'&&wc.navigationHistory.canGoBack())wc.navigationHistory.goBack();else if(name==='reload'){this.error='';wc.loadURL(this.requested||wc.getURL()).catch(()=>{});}this.publish();}
}
module.exports={PublicBrowser,publicAddress,address};
